In [1]:
import requests

from bs4 import BeautifulSoup
import pandas as pd
import time
import numpy as np

In [9]:
nutrients = pd.read_csv('sites.csv')
nutrients = nutrients.drop(columns=['URL 1 Context','URL 2 Context', 'URL 3 Context'])
nutrients.head()

Nutrient                                      URL 1  \
0  Vitamin A   https://www.mdpi.com/2072-6643/13/5/1703   
1  Vitamin C  https://www.mdpi.com/1422-0067/20/19/4735   
2       Iron  https://www.mdpi.com/1422-0067/20/19/4968   
3  Vitamin D  https://www.mdpi.com/1422-0067/20/19/4907   
4  Vitamin E    https://www.mdpi.com/2076-3921/11/5/989   

                                               URL 2  \
0           https://www.mdpi.com/2072-6643/14/6/1312   
1           https://www.mdpi.com/2072-6643/12/5/1501   
2            https://www.mdpi.com/1422-0067/24/1/449   
3          https://www.mdpi.com/1422-0067/21/18/6573   
4  https://www.wjgnet.com/1949-8454/full/v7/i1/14...   

                                               URL 3  
0           https://www.mdpi.com/1422-0067/23/3/1014  
1             https://www.mdpi.com/2072-6643/9/8/866  
2             https://www.mdpi.com/1422-0067/20/1/95  
3           https://www.mdpi.com/1422-0067/18/9/1949  
4  https://www.dovepress.com/pharmacology-and-pha...

In [30]:
def ncbi_enzyme_search(urls):
    enzymes = []
    
    for x in urls:
        
        response = requests.get(x)

        soup = BeautifulSoup(response.content, 'html.parser')
        text = soup.get_text()


        text = text.replace(".", "")
        text = text.replace(':','')
        text = text.replace(',','')
        text = text.replace('-',' ')
        text = text.replace("'",'')
        text = text.replace('(','')
        text = text.replace(')','')
        text = text.replace('=','')
        text = text.replace('"','')

        text = text.split()

        not_useful_ase = ['case', 'cases', 'increase', 'increases', 'increased', 'increasing','decrease', 'decreases', 'decreased','decreasing','release','releases','released','releasing','cease','ceases','ceased','ceasing','base','bases','based','disease','diseases','database','Cases','cerealbased','baseline','proteinbased','plantbased','increasesThe','grease','greases','greased','D3based', 'Disease', 'Diseases', 'Diseased', 'Increase','Increases','Increased','Decrease','Decreased','Decreases','Database','please','pleases','pleased''Please','Pleases','Pleased','diseases.','disease:','disease.','Disease:','Disease.']

        for x in text:
            ase = 'ase'
            if x not in not_useful_ase and ase in x:
                enzymes.append(x)

        
        
            
    return enzymes

In [11]:
oxidoreductase = ['oxidase', 'dehydrogenase', 'desaturase', 'peroxidase', '4-hydroxylase', 'reductase', 'dehydrogenase/reductase','dehydrogenases','reductasesretinal','dehydrogenaseretinal','1515dioxygenase','1515monooxygenase','15monooxygenase','prolyl3hydroxylases','prolyl4hydroxylases','hydroxylases','hydroxylase','dioxygenase', 'betahydroxylase', 'monooxygenase', 'oxidases','6dehydrogenase','25hydroxylase', '1alphahydroxylase', '24hydroxylase', '27hydroxylase','hydrogenases','nitrogenase','lipoxygenases','catalase','deiodinases','deiodinase','peroxidases','Deiodinases','iodinase','dehydrogenasebranched', 'dehydrogenase2','laccases','tyrosinases','reductaseChemical','oxidoreductases','phenoloxidase', 'nitrogenases','Nitrogenases','oxidoreductase']
transferase = ['kinase','6-beta-N-acetylglucosaminyltransferase','glucosyltransferase', 'isopentenyltransferase', 'sulfotransferase','acyltransferase','transferase','pyrophosphorylase','glucuronokinase','carboxylase','transaminase','Transaminases','phosphorylase','transaminases','aminotransferase','vitaminMethyltransferasesMethyl','methyltransferase','diphosphokinase','transketolase','kinaseThe','thiaminases', 'thiaminase','kinase;','polymerase','polymerases','hydroxymethyltransferase','carboxylases','transferaseFinally','transferases','kinases','cytidylyltransferases','acetyltransferase','Kinases','carboxykinase','[53]Phosphofructokinase']
hydrolase = ['deaminase', 'GTPase', 'GTPase,', 'ATPase', 'ATPases' 'metallopeptidase', 'caspase', 'phosphatase', 'beta-secretase', 'glutaminase', 'endonuclease', 'dihydropyrimidinase', 'peptidase', 'helicase', 'alpha-L-fucosidase', 'carboxypeptidase', 'phosphodiesterase','hydrolases','hydrolase','gluconolactonase—between','phosphatases','vitaminDehalogenasesSome', 'dehalogenases','proteases','glucosidase','pyrophosphatase','conjugase','biotinidase','Biotinidase','sulfoxideBiotinidase','Pantetheinase','fermentationCarboxypeptidase','arginase','transcriptases','amylase','cholinephosphotransferase','phospholipases','acetylcholinesterase','Phosphatases','Enolase','helicases','exonucleases']
lyase = ['cyclase', 'lyase', 'anhydrase','cystathionase','lyasetransketolasePresent','decarboxylase','hydratase','decarboxylase4′','lyases','Aldolase']
isomerase = ['racemase','animalsIsomerasesRearrangements','isomerase','isomerases','mutase','dismutase','dismutases','topoisomerases']
ligase = ['synthetase', 'synthase','cosynthetase','synthaseThe','synthase;','ligase','synthetaseValproic','holocarboxylase','synthetaseBiotinylation','Holocarboxylase','ligases']
translocase = ['scramblase']

ec = [oxidoreductase, transferase, hydrolase, lyase, isomerase, ligase, translocase]

In [12]:
def enzyme_classify(enzyme_list):
    
    vit_distribution= []

    for x in range(len(enzyme_list)):
        if enzyme_list[x] in ec[0]:
            vit_distribution.append(1)
        elif enzyme_list[x] in ec[1]:
            vit_distribution.append(2)
        elif enzyme_list[x] in ec[2]:
            vit_distribution.append(3)
        elif enzyme_list[x] in ec[3]:
            vit_distribution.append(4)
        elif enzyme_list[x] in ec[4]:
            vit_distribution.append(5)
        elif enzyme_list[x] in ec[5]:
            vit_distribution.append(6)
        elif enzyme_list[x] in ec[6]:
            vit_distribution.append(7)
        else:
            vit_distribution.append(0)
            
    return vit_distribution

In [13]:
##need to edit this portion

In [32]:
def vit_rat_dict_v2(vit_list):
    
    history= []
    
    dict_rat ={}
    
    for x in range(len(vit_list)):
        if vit_list[x] not in history and vit_list[x] != 0:
            y = (vit_list.count(vit_list[x]))/len([i for i in vit_list if i !=0])
            z = vit_list[x]
            dict_rat[z]= y
            history.append(list[x])
        elif list[x] in history:
            print('no')
            
    return dict_rat

In [15]:
def nutrient_overall_url(url):
    nutr_enzymes = ncbi_enzyme_search(url)

    #print (nutr_enzymes)
    #print (len(nutr_enzymes))
    
    nutr_distribution = enzyme_classify(nutr_enzymes)

    #print (nutr_distribution)

    ratio_nutr = vit_rat_dict(nutr_distribution)

    #print (ratio_nutr)

In [33]:
def nutrient_dataframe_third(df):
    df_list = []
    for x in range(len(df)):
        i=0
        y=[]
        while i <3:
            y.append(df.iloc[x,i+1])
            i += 1
    
        nutr_enzymes = ncbi_enzyme_search(y)
    
        nutr_distribution = enzyme_classify(nutr_enzymes)

        ratio_nutr = vit_rat_dict_v2(nutr_distribution)
    
        df_list.append(ratio_nutr)
        i += 1
    
    df_nutr = pd.DataFrame(data=df_list)
    
    return df_nutr

In [34]:
test = nutrient_dataframe_third(nutrients)
print (test)

           2         3         1         5         6         4
0   0.305556  0.062500  0.625000  0.006944       NaN       NaN
1   0.189189  0.148649  0.527027  0.081081  0.054054       NaN
2   0.226190  0.119048  0.511905  0.011905  0.130952       NaN
3   0.256757  0.121622  0.567568       NaN  0.040541  0.013514
4   0.250000  0.075000  0.650000  0.025000       NaN       NaN
5   0.531915  0.148936  0.276596       NaN  0.042553       NaN
6   0.440000  0.030000  0.450000       NaN  0.020000  0.060000
7   0.086364  0.054545  0.759091       NaN  0.100000       NaN
8   0.525773  0.185567  0.216495       NaN  0.061856  0.010309
9   0.237374  0.106061  0.267677  0.005051  0.252525  0.131313
10  0.076923  0.092308  0.476923       NaN  0.353846       NaN
11  0.250000  0.283333  0.133333  0.116667  0.216667       NaN
12  0.291045  0.067164  0.044776       NaN  0.589552  0.007463
13  0.296703  0.076923  0.120879       NaN  0.153846  0.351648
14  0.235294  0.352941  0.411765       NaN       NaN   

In [35]:
test = test.fillna(0)

In [37]:
test = test.T

In [41]:
test = test.sort_index(ascending=True)

In [44]:
columns= ['vitamin_a','vitamin_c','vitamin_d','vitamin_e','vitamin_k','vitamin_b6','vitamin_b12', 'iron','calcium','selenium','iodine','thiamin','riboflavin','niacin','folate','biotin','pantothenic_acid','phosphorus','magnesium','zinc','copper','manganese','chromium','molybdenum','chloride','potassium','choline']

In [47]:
column_dict = {}
for x in range(27):
    column_dict[x] = columns[x]
    
print (column_dict)    

{0: 'vitamin_a', 1: 'vitamin_c', 2: 'vitamin_d', 3: 'vitamin_e', 4: 'vitamin_k', 5: 'vitamin_b6', 6: 'vitamin_b12', 7: 'iron', 8: 'calcium', 9: 'selenium', 10: 'iodine', 11: 'thiamin', 12: 'riboflavin', 13: 'niacin', 14: 'folate', 15: 'biotin', 16: 'pantothenic_acid', 17: 'phosphorus', 18: 'magnesium', 19: 'zinc', 20: 'copper', 21: 'manganese', 22: 'chromium', 23: 'molybdenum', 24: 'chloride', 25: 'potassium', 26: 'choline'}


In [48]:
test = test.rename(columns=column_dict)

In [72]:
test['enzyme_class']= {1:1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7}

In [73]:
test.head(6)

vitamin_a  vitamin_c  vitamin_d  vitamin_e  vitamin_k  vitamin_b6  \
1   0.625000   0.527027   0.511905   0.567568      0.650    0.276596   
2   0.305556   0.189189   0.226190   0.256757      0.250    0.531915   
3   0.062500   0.148649   0.119048   0.121622      0.075    0.148936   
4   0.000000   0.000000   0.000000   0.013514      0.000    0.000000   
5   0.006944   0.081081   0.011905   0.000000      0.025    0.000000   
6   0.000000   0.054054   0.130952   0.040541      0.000    0.042553   

   vitamin_b12      iron   calcium  selenium  ...  magnesium      zinc  \
1         0.45  0.759091  0.216495  0.267677  ...   0.140625  0.742857   
2         0.44  0.086364  0.525773  0.237374  ...   0.273438  0.061905   
3         0.03  0.054545  0.185567  0.106061  ...   0.128906  0.028571   
4         0.06  0.000000  0.010309  0.131313  ...   0.019531  0.009524   
5         0.00  0.000000  0.000000  0.005051  ...   0.332031  0.000000   
6         0.02  0.100000  0.061856  0.252525  ...   0.105469  0.157143   

     copper  manganese  chromium  molybdenum  chloride  potassium   choline  \
1  0.058252   0.022901  0.253731    0.173469  0.210526       0.03  0.606742   
2  0.368932   0.053435  0.388060    0.428571  0.443609       0.69  0.179775   
3  0.495146   0.824427  0.134328    0.306122  0.323308       0.19  0.123596   
4  0.038835   0.000000  0.104478    0.030612  0.000000       0.01  0.000000   
5  0.000000   0.000000  0.000000    0.030612  0.000000       0.01  0.078652   
6  0.038835   0.099237  0.119403    0.030612  0.022556       0.07  0.011236   

   enzyme_class  
1             1  
2             2  
3             3  
4             4  
5             5  
6             6  

[6 rows x 28 columns]

In [4]:
df= pd.read_excel('Table_S2.xlsx')
df.columns = df.iloc[1]
df = df.drop([0,1])
df.reset_index()
df = df.astype({'membership': 'float64'})
df = df.astype({'traitsig': 'float64'})
df = df.astype({'LV_number': 'category'})

In [5]:
import requests 
from bs4 import BeautifulSoup 
import bs4

In [97]:
def kegg_api_find_hsa(gene_list):
    hsa_list_final = []
    for x in gene_list:
        URL = f'https://rest.kegg.jp/find/genes/{x}'
        r = requests.get(URL) 
        soup = bs4.BeautifulSoup(r.content, 
                             "lxml") 
        heading_object=soup.find_all( 'p' )
        
        soup_list = str(heading_object)

        soup_list = list(soup_list.split())
        
        hsa_list= []
        for y in soup_list:
            hsa_tag_pre = []
            hsa = []
            insert = 'hsa:'
            if insert in y:
                for z in y:
                    hsa_tag_pre.append(z)
                start = hsa_tag_pre.index('h')
                hsa = hsa_tag_pre[start:]
                hsa_tag = (''.join(hsa))
                hsa_list.append(hsa_tag)


            else:
                x=x
        if hsa_list != []:
            hsa_list_final.append(hsa_list[0])
            
    return hsa_list_final

In [115]:
gene_urls = list(df['gene'])
print (len(gene_urls))

307


In [99]:
retrieval_test = kegg_api_find_hsa(gene_urls)
print (retrieval_test)

['hsa:10964', 'hsa:103', 'hsa:7188', 'hsa:9938', 'hsa:10461', 'hsa:4249', 'hsa:1293', 'hsa:9881', 'hsa:89876', 'hsa:5359', 'hsa:59345', 'hsa:55351', 'hsa:57205', 'hsa:23061', 'hsa:9180', 'hsa:5734', 'hsa:10769', 'hsa:2151', 'hsa:84695', 'hsa:5272', 'hsa:54551', 'hsa:200424', 'hsa:55303', 'hsa:10863', 'hsa:9991', 'hsa:3087', 'hsa:840', 'hsa:4940', 'hsa:221178', 'hsa:115207', 'hsa:10681', 'hsa:51069', 'hsa:54739', 'hsa:81035', 'hsa:7576', 'hsa:5786', 'hsa:25825', 'hsa:25966', 'hsa:5613', 'hsa:3098', 'hsa:1193', 'hsa:29899', 'hsa:51279', 'hsa:23114', 'hsa:8788', 'hsa:220', 'hsa:2760', 'hsa:8795', 'hsa:25796', 'hsa:6402', 'hsa:9627', 'hsa:81567', 'hsa:10875', 'hsa:10068', 'hsa:401115', 'hsa:113', 'hsa:140893', 'hsa:1820', 'hsa:94039', 'hsa:9770', 'hsa:5634', 'hsa:203427', 'hsa:439996', 'hsa:100526664', 'hsa:10877', 'hsa:1992', 'hsa:64859', 'hsa:51176', 'hsa:1462', 'hsa:4001', 'hsa:4593', 'hsa:84922', 'hsa:342510', 'hsa:30817', 'hsa:162966', 'hsa:2048', 'hsa:214', 'hsa:493869', 'hsa:59335',

In [100]:
print (len(retrieval_test))

227


In [112]:
def gene_to_enzyme_class(hsa_list):
        classification_list=[]
        for hsa in hsa_list:
            URL = f'https://rest.kegg.jp/link/enzyme/{hsa}'
            r = requests.get(URL) 
            soup = bs4.BeautifulSoup(r.content, "lxml") 
            heading_object=soup.find_all( 'p' )

            if heading_object == []:
                print ('None')
            else:
                listed = str(heading_object)
                soup_list = list(listed.split())

                for x in soup_list:
                    if 'ec' in x:
                        ec_list =[]
                        for y in x:
                            ec_list.append(y)
                        ind = ec_list.index(':')
                classification = ec_list[ind+1]

                classification_list.append(classification)

        
        return classification_list

In [113]:
retrieval_test_2 = gene_to_enzyme_class(retrieval_test)
print (retrieval_test_2)

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
['3', '2', '2', '2', '7', '2', '1', '3', '2',

In [114]:
print (len(retrieval_test_2))

36


In [93]:
df.head(10)

1  module  membership  traitsig        ensg_version      gene LV_number  \
2     red      0.5158    0.2172  ENSG00000137959.15    IFI44L         2   
3     red      0.5497    0.4713  ENSG00000160710.16      ADAR         2   
4     red      0.7754    0.5447  ENSG00000082512.14     TRAF5         2   
5     red      0.7309    0.4325  ENSG00000163219.11  ARHGAP25         2   
6     red      0.5587    0.4396  ENSG00000153208.16     MERTK         2   
7     red      0.6029    0.5140   ENSG00000152127.8     MGAT5         2   
8     red      0.4493    0.3355  ENSG00000163359.15    COL6A3         2   
9     red      0.8284    0.6855  ENSG00000168016.14    TRANK1         2   
10    red      0.5252    0.5227  ENSG00000183833.16    MAATS1         2   
11    red      0.7394    0.5133  ENSG00000188313.12    PLSCR1         2   

1                LV_pathway  
2   MetaMEx_AerobicTraining  
3   MetaMEx_AerobicTraining  
4   MetaMEx_AerobicTraining  
5   MetaMEx_AerobicTraining  
6   MetaMEx_AerobicTraining  
7   MetaMEx_AerobicTraining  
8   MetaMEx_AerobicTraining  
9   MetaMEx_AerobicTraining  
10  MetaMEx_AerobicTraining  
11  MetaMEx_AerobicTraining

In [54]:
import re
from collections import defaultdict
from io import BytesIO, StringIO
from pathlib import Path
from zipfile import ZipFile
import matplotlib.pyplot as plt
from Bio import AlignIO, Phylo, SeqIO
from Bio.Align.Applications import MuscleCommandline
from Bio.Phylo.TreeConstruction import (
    NNITreeSearcher,
    ParsimonyScorer,
    ParsimonyTreeConstructor,
)
from Bio.SeqRecord import SeqRecord
from ncbi.datasets import GeneApi

/opt/anaconda3/lib/python3.11/site-packages/Bio/Application/__init__.py:40: BiopythonDeprecationWarning: The Bio.Application modules and modules relying on it have been deprecated.

Due to the on going maintenance burden of keeping command line application
wrappers up to date, we have decided to deprecate and eventually remove these
modules.

We instead now recommend building your command line and invoking it directly
with the subprocess module.
  warnings.warn(


In [55]:
taxon = 'human'
symbols = df['gene'].tolist()
print (type(symbols))

gene_api = GeneApi()

<class 'list'>


In [56]:
metadata = gene_api.gene_metadata_by_tax_and_symbol(symbols, taxon)

In [57]:
gene_des = {}

for gene_data in metadata.genes:
    
    x = gene_data.gene.description
    y = gene_data.gene.symbol
    
    gene_des[y] = x
    
### an attribute error arises but it is fine please proceed    

AttributeError: 'NoneType' object has no attribute 'description'

In [58]:
keys = []
values = []

for key,value in gene_des.items():
    keys.append(key)
    values.append(value)
    

data = {'gene': keys,
        'enzyme_des': values}

df_des = pd.DataFrame(data)


print (df_des.head())
df_des.describe()

        gene                                  enzyme_des
0     HOTAIR                HOX transcript antisense RNA
1  LINC00892  long intergenic non-protein coding RNA 892
2  LINC00605  long intergenic non-protein coding RNA 605
3     IPO5P1                     importin 5 pseudogene 1
4   GOLGA8DP       golgin A8 family member D, pseudogene


gene                    enzyme_des
count      264                           264
unique     264                           264
top     HOTAIR  HOX transcript antisense RNA
freq         1                             1

In [59]:
enz_list = []

for x in df_des['enzyme_des']:
    ase = 'ase'
    li_st = [i for i in x.split() if ase in i ]
    if li_st == []:
        li_st_ = 'other'
    else:
        li_st_ = li_st[0]
    
    enz_list.append(li_st_)
        
print (enz_list)
print(len(enz_list))

['other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'deaminase', 'other', 'other', 'carboxypeptidase', 'other', 'kinase', 'other', 'kinase', 'other', 'metallopeptidase', 'other', 'other', 'other', 'other', 'other', 'kinase', 'anhydrase', 'cyclase', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'kinase', 'other', 'other', 'other', 'other', 'other', 'kinase', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'dehydrogenase', 'other', 'other', 'other', 'other', 'other', 'other', 'other', 'kinase', 'other', 'GTPase', 'other', 'alpha-L-fucosidase', 'kinase', 'other', 'beta-secretase', 'other', 'other', 'other', 'other', 'o

In [60]:
data_2 = {'gene': keys,
        'assoc_enzymes': enz_list}

df_enz = pd.DataFrame(data_2)


print (df_enz.head())
df_enz.describe()

        gene assoc_enzymes
0     HOTAIR         other
1  LINC00892         other
2  LINC00605         other
3     IPO5P1         other
4   GOLGA8DP         other


gene assoc_enzymes
count      264           264
unique     264            35
top     HOTAIR         other
freq         1           212

In [61]:
df_2 = df.merge(df_enz, how='inner', on='gene')

df_2.head()

module  membership  traitsig        ensg_version      gene LV_number  \
0    red      0.5158    0.2172  ENSG00000137959.15    IFI44L         2   
1    red      0.5497    0.4713  ENSG00000160710.16      ADAR         2   
2    red      0.7754    0.5447  ENSG00000082512.14     TRAF5         2   
3    red      0.7309    0.4325  ENSG00000163219.11  ARHGAP25         2   
4    red      0.5587    0.4396  ENSG00000153208.16     MERTK         2   

                LV_pathway assoc_enzymes  
0  MetaMEx_AerobicTraining         other  
1  MetaMEx_AerobicTraining     deaminase  
2  MetaMEx_AerobicTraining         other  
3  MetaMEx_AerobicTraining        GTPase  
4  MetaMEx_AerobicTraining        kinase

In [62]:
df_2_without_other = df_2[df_2['assoc_enzymes'] != 'other']

df_2_without_other.describe()

membership   traitsig
count   50.000000  50.000000
mean     0.586992   0.406314
std      0.110572   0.143765
min      0.303700   0.082200
25%      0.497425   0.313175
50%      0.602200   0.396450
75%      0.677300   0.513150
max      0.760100   0.639500

In [63]:
s1 = df['gene']
s2 = df_enz['gene']
df_compare = pd.concat([s1,s2])

print(df_compare)

2        IFI44L
3          ADAR
4         TRAF5
5      ARHGAP25
6         MERTK
         ...   
259      RASSF2
260      TRANK1
261    RABGAP1L
262    ARHGAP25
263       PTBP3
Name: gene, Length: 571, dtype: object


In [64]:
duplicated = df_compare[df_compare.duplicated() == True].tolist()
duplicated_set = set(duplicated)

ncbi_gene_list = df_enz['gene'].tolist()
ncbi_gene_set = set(ncbi_gene_list)

diff = ncbi_gene_set - duplicated_set

print (diff)

{'IFTAP', 'DYNLT4', 'ACP3', 'SEPTIN6', 'SLC66A3', 'TLCD5', 'FCGR1BP', 'H2BC26', 'DIPK1C', 'TASL', 'CFAP91', 'PABIR2'}


In [65]:
orig_gene_list = df['gene'].tolist()
orig_gene_set = set(orig_gene_list)

ncbi_diff = orig_gene_set - ncbi_gene_set

print (ncbi_diff)

{'AC245100.4', 'AC131097.4', 'AC011511.4', 'TCTEX1D4', 'FAM122B', 'AC104663.1', 'AC106795.5', 'AL031595.1', 'AP000525.1', 'AL161785.1', 'AP001646.2', 'CXorf21', 'AL021328.1', 'AC099548.2', 'PQLC3', 'AL109811.2', 'AC244502.1', 'MAATS1', 'AC091488.1', 'AL034397.3', 'AC114271.1', 'C11orf74', 'AC012313.2', 'AC098484.3', 'AC098820.2', 'FAM69C', 'AC027702.1', 'AL133355.1', 'AC105749.1', 'AL353746.1', 'AL606760.1', 'AC008581.1', 'AF117829.1', 'AC104772.1', 'ACPP', 'AL445472.1', 'AL359762.1', 'AC004847.1', 'AD000864.1', 'SEPT6', 'AC113382.2', 'AC012485.3', 'FP565260.3', 'AL365209.1', 'AC020915.3', 'AC125611.3', 'TMEM136', 'AC019257.7', 'AF127936.2', 'AC131902.2', 'AL731533.2', 'AC011477.1', 'HIST3H2BB', 'FCGR1B', 'AC069209.1'}


In [66]:
diff_as_a_list = list(diff)

df_enz_without_other_and_set = df_enz[df_enz['gene'].isin(diff_as_a_list)]

print (df_enz_without_other_and_set)

        gene assoc_enzymes
46     IFTAP         other
50    DIPK1C        kinase
52    H2BC26         other
55   SLC66A3         other
67    PABIR2         other
82     TLCD5         other
85   FCGR1BP         other
88   SEPTIN6         other
125   DYNLT4         other
176     ACP3   phosphatase
222     TASL         other
242   CFAP91         other


In [67]:
row_number_FAM69C = df[df['gene'] == 'FAM69C'].index

print(row_number_FAM69C)

print (df.iloc[253])

row_number_ACPP = df[df['gene'] == 'ACPP'].index

print(row_number_ACPP)

print (df.iloc[141])

FAM69C_row = {'membership': 0.4532, 'traitsig': 0.3218, 'ensg_version': 'ENSG00000187773.8', 'gene': 'FAM69C', 'LV_number': None, 'LV_pathway':None , 'assoc_enzymes':'kinase'}

df_2.loc[len(df_2)] = FAM69C_row

ACPP_row = {'membership': 0.6015, 'traitsig': 0.4211, 'ensg_version': 'ENSG00000014257.15', 'gene': 'ACPP', 'LV_number':None , 'LV_pathway':None , 'assoc_enzymes':'phosphatase'}

df_2.loc[len(df_2)] = ACPP_row

Index([255], dtype='int64')
1
module                        red
membership                 0.4532
traitsig                   0.3218
ensg_version    ENSG00000187773.8
gene                       FAM69C
LV_number                     NaN
LV_pathway                    NaN
Name: 255, dtype: object
Index([143], dtype='int64')
1
module                         red
membership                  0.6015
traitsig                    0.4211
ensg_version    ENSG00000014257.15
gene                          ACPP
LV_number                      NaN
LV_pathway                     NaN
Name: 143, dtype: object


/var/folders/w4/swg_x0mn7sl_p9j90gy4tmk80000gn/T/ipykernel_1620/3250359206.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_2.loc[len(df_2)] = FAM69C_row
/var/folders/w4/swg_x0mn7sl_p9j90gy4tmk80000gn/T/ipykernel_1620/3250359206.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_2.loc[len(df_2)] = ACPP_row


In [68]:
df_2_without_other = df_2[df_2['assoc_enzymes'] != 'other']

df_2_without_other.describe()

membership   traitsig
count   52.000000  52.000000
mean     0.584698   0.404973
std      0.109984   0.141422
min      0.303700   0.082200
25%      0.495275   0.316325
50%      0.601500   0.396450
75%      0.675900   0.512850
max      0.760100   0.639500

In [69]:
oxidoreductase = ['oxidase', 'dehydrogenase', 'desaturase', 'peroxidase', '4-hydroxylase', 'reductase', 'dehydrogenase/reductase']
transferase = ['kinase','6-beta-N-acetylglucosaminyltransferase','glucosyltransferase', 'isopentenyltransferase', 'sulfotransferase']
hydrolase = ['deaminase', 'GTPase', 'GTPase,', 'ATPase', 'metallopeptidase', 'caspase', 'phosphatase', 'beta-secretase', 'glutaminase', 'endonuclease', 'dihydropyrimidinase', 'peptidase', 'helicase', 'alpha-L-fucosidase', 'carboxypeptidase', 'phosphodiesterase']
lyase = ['cyclase', 'lyase', 'anhydrase']
isomerase = []
ligase = ['synthetase', 'synthase']
translocase = ['scramblase']

ec = [oxidoreductase, transferase, hydrolase, lyase, isomerase, ligase, translocase]

enzyme_class = []

for x in range(len(df_2['assoc_enzymes'])):
    if df_2['assoc_enzymes'][x] in ec[0]:
        enzyme_class.append(1)
    elif df_2['assoc_enzymes'][x] in ec[1]:
        enzyme_class.append(2)
    elif df_2['assoc_enzymes'][x] in ec[2]:
        enzyme_class.append(3)
    elif df_2['assoc_enzymes'][x] in ec[3]:
        enzyme_class.append(4)
    elif df_2['assoc_enzymes'][x] in ec[5]:
        enzyme_class.append(6)
    elif df_2['assoc_enzymes'][x] in ec[6]:
        enzyme_class.append(7)
    else:
        enzyme_class.append(0)

In [70]:
df_2['enzyme_class'] = enzyme_class

print (df_2.head())

  module  membership  traitsig        ensg_version      gene LV_number  \
0    red      0.5158    0.2172  ENSG00000137959.15    IFI44L         2   
1    red      0.5497    0.4713  ENSG00000160710.16      ADAR         2   
2    red      0.7754    0.5447  ENSG00000082512.14     TRAF5         2   
3    red      0.7309    0.4325  ENSG00000163219.11  ARHGAP25         2   
4    red      0.5587    0.4396  ENSG00000153208.16     MERTK         2   

                LV_pathway assoc_enzymes  enzyme_class  
0  MetaMEx_AerobicTraining         other             0  
1  MetaMEx_AerobicTraining     deaminase             3  
2  MetaMEx_AerobicTraining         other             0  
3  MetaMEx_AerobicTraining        GTPase             3  
4  MetaMEx_AerobicTraining        kinase             2  


In [74]:
df_merge = df_2.merge(test, left_on='enzyme_class', right_on='enzyme_class', how='left')

print (df_merge.head(10))

  module  membership  traitsig        ensg_version      gene LV_number  \
0    red      0.5158    0.2172  ENSG00000137959.15    IFI44L         2   
1    red      0.5497    0.4713  ENSG00000160710.16      ADAR         2   
2    red      0.7754    0.5447  ENSG00000082512.14     TRAF5         2   
3    red      0.7309    0.4325  ENSG00000163219.11  ARHGAP25         2   
4    red      0.5587    0.4396  ENSG00000153208.16     MERTK         2   
5    red      0.6029    0.5140   ENSG00000152127.8     MGAT5         2   
6    red      0.4493    0.3355  ENSG00000163359.15    COL6A3         2   
7    red      0.8284    0.6855  ENSG00000168016.14    TRANK1         2   
8    red      0.7394    0.5133  ENSG00000188313.12    PLSCR1         2   
9    red      0.6431    0.7271   ENSG00000114450.9      GNB4         2   

                LV_pathway                           assoc_enzymes  \
0  MetaMEx_AerobicTraining                                   other   
1  MetaMEx_AerobicTraining                   

In [75]:
df_merge.to_csv('wrangled_data_revised.csv')

In [1]:
import requests 
from bs4 import BeautifulSoup 
import bs4
from rcsbsearchapi.search import TextQuery
from rcsbsearchapi import rcsb_attributes as attrs

In [2]:
def pdb_parse(gene_list):
    second_check_genes = []
    results = {}
    for gene in gene_list:
        print (gene)
        URL = f'https://rest.kegg.jp/find/genes/{gene}'
        r = requests.get(URL) 
        soup = bs4.BeautifulSoup(r.content, 
                                 "lxml") 
        print (len(soup))
        if len(soup) == 0:
            second_check_genes.append(gene)
            results[gene] = []
            continue
        
        heading_object=soup.find_all( 'p' )
        soup_list = str(heading_object)
        soup_list = list(soup_list.split())


        pre_container = []
        tags = [':',',',';']
        length = 0
        protein = []
        for x in soup_list:
            if ';' in x and length == 0:    
                print (True)

            elif ',' in x and length == 0:    
                print (True)

            elif ':' in x and length == 0:    
                print (True)


            elif ';' not in x and ',' not in x and ':' not in x : 
                length += 1
                protein.append(x)


            elif ';' in x and length > 0:
                print (protein)
                break

            elif ',' in x and length > 0:
                print (protein)
                break

            elif ':' in x and length > 0:
                print (protein)
                break
        
        if len(protein) < 3:
            second_check_genes.append(gene)
        
        combined_word = str()
        for x in protein:
            word = x
            combined_word = ' '.join([combined_word , word])
            
        q1 = TextQuery(f"{combined_word}")

        # add parameter as a list with either "computational" or "experimental" or both as list values
        q2 = q1(return_content_type=["experimental"])

        q3 =  (list(q2))
        q4 = [x for x in q3 if len(x) == 4]
        
        print (q4[0])
        
        url = f'https://www.ebi.ac.uk/pdbe/api/pdb/entry/ligand_monomers/{q4[0]}'
        r = requests.get(url) 
        soup = bs4.BeautifulSoup(r.content, 
                                     "lxml") 
        query=soup.find_all( 'p' ) 


        comp_list = []
        start=0
        end=0

        for x in query:
            x = str(x)
            for y in range(len(x)):
                if x[y] =='c' and x[y+1]== 'h' and x[y+10] == 'n':
                        start = y + 17 
                elif start != 0 and x[y] == '"' and x[y+1] == ',':
                        end = y
                if start != 0 and end != 0:
                        comp_list.append(x[start:end])
                        start = 0
                        end= 0

        results[gene] = comp_list
        print (len(comp_list)) 
        
        
    return results, second_check_genes

In [89]:
gene_list_1 = list(df['gene'][0:50])
gene_list_2 = list(df['gene'][50:100])
gene_list_3 = list(df['gene'][100:150])
gene_list_4 = list(df['gene'][150:200])
gene_list_5 = list(df['gene'][200:250])
gene_list_6 = list(df['gene'][250:308])

In [103]:
print (gene_list_2)

['SNCA', 'TXNDC5', 'FGL2', 'IL18BP', 'NELL2', 'ADCY7', 'RBBP8', 'ARID3A', 'ZNF101', 'RASSF2', 'PRPS2', 'SLC25A43', 'IL6R-AS1', 'IFIT1', 'LY75', 'CFH', 'SERPINB1', 'NABP1', 'LEF1', 'VCAN', 'LMNB1', 'FADS1', 'FLT3', 'CD300E', 'ADGRE2', 'ZNF600', 'EPHB2', 'ALCAM', 'GPX8', 'PRDM1', 'UGCG', 'CHEK1', 'CACNA2D4', 'LTB4R', 'SYT17', 'CASS4', 'PTGFRN', 'LHFPL2', 'P4HA2', 'LUM', 'TNFRSF19', 'DOCK8', 'SLC2A3', 'OASL', 'GNG2', 'SLC24A4', 'BTG3', 'AL109811.2', 'AL365209.1', 'SPOCD1']


In [91]:
results_1 = pdb_parse(gene_list_1)

IFI44L
1
True
True
True
True
True
['interferon', 'induced', 'protein', '44', 'like']
7JL2
12
ADAR
1
True
True
True
True
True
True
True
True
True
True
True
True
['adenosine', 'deaminase', 'RNA', 'specific']
7BV5
4
TRAF5
1
True
True
True
True
['TNF', 'receptor', 'associated', 'factor', '5']
4GJH
0
ARHGAP25
1
True
True
True
True
['Rho', 'GTPase', 'activating', 'protein', '25']
1V89
0
MERTK
1
True
True
True
True
True
True
True
['MER']
6BY7
0
MGAT5
1
True
True
True
True
True
True
True
['6-beta-N-acetylglucosaminyltransferase']
7JHO
29
COL6A3
1
True
True
True
True
True
True
True
['collagen', 'type', 'VI', 'alpha', '3', 'chain']
1KTH
2
TRANK1
1
True
True
True
['tetratricopeptide', 'repeat', 'and', 'ankyrin', 'repeat', 'containing', '1']
5AAO
6
MAATS1
1
True
True
True
True
True
True
True
True
True
['cilia', 'and', 'flagella', 'associated', 'protein', '91']
8TEK
0
PLSCR1
1
True
True
True
['phospholipid', 'scramblase', '1']
7RXB
8
GNB4
1
True
True
True
True
['G', 'protein', 'subunit', 'beta', '4

In [95]:
print (results_1[0])

{'IFI44L': ['ZINC ION', 'ZINC ION', 'ZINC ION', "ADENOSINE-5'-DIPHOSPHATE", "ADENOSINE-5'-DIPHOSPHATE", "ADENOSINE-5'-DIPHOSPHATE", 'TETRAFLUOROALUMINATE ION', 'TETRAFLUOROALUMINATE ION', 'TETRAFLUOROALUMINATE ION', 'MAGNESIUM ION', 'MAGNESIUM ION', 'MAGNESIUM ION'], 'ADAR': ['ZINC ION', 'ZINC ION', 'ZINC ION', 'ZINC ION'], 'TRAF5': [], 'ARHGAP25': [], 'MERTK': [], 'MGAT5': ["URIDINE-5'-DIPHOSPHATE", "URIDINE-5'-DIPHOSPHATE", 'MAGNESIUM ION', 'MAGNESIUM ION', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'CHLORIDE ION', 'CHLORIDE ION', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-D-mannopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-D-mannopyranose', 

In [105]:
results_2 = pdb_parse(gene_list_2)

SNCA
1
True
True
True
True
['synuclein', 'alpha', 'interacting', 'protein']
2KES
0
TXNDC5
1
True
True
True
True
True
True
True
True
True
['thioredoxin', 'domain', 'containing', '5']
1F6M
8
FGL2
1
True
True
True
True
['fibrinogen', 'like', '2']
6Y41
20
IL18BP
1
True
True
True
True
['interleukin', '18', 'binding', 'protein']
7FCH
0
NELL2
1
True
True
True
True
True
['NELL2', 'interacting', 'cell', 'ontogeny', 'regulator', '1']
6POG
7
ADCY7
1
True
True
True
['adenylate', 'cyclase', '7']
5X4V
1
RBBP8
1
True
True
True
['RBBP8', 'N-terminal', 'like']
7BGF
0
ARID3A
1
True
True
True
True
True
True
['AT-rich', 'interaction', 'domain', '3A']
2KK0
0
ZNF101
1
True
True
True
['zinc', 'finger', 'protein', '101']
1U6P
1
RASSF2
1
True
True
True
True
['Ras', 'association', 'domain', 'family', 'member', '2']
2CS4
0
PRPS2
1
True
True
True
['phosphoribosyl', 'pyrophosphate', 'synthetase', '2']
1DKR
4
SLC25A43
1
True
True
['solute', 'carrier', 'family', '25', 'member', '43']
3GNU
3
IL6R-AS1
0
IFIT1
1
True
T

In [106]:
print (results_2[0])

{'SNCA': [], 'TXNDC5': ['FLAVIN-ADENINE DINUCLEOTIDE', 'FLAVIN-ADENINE DINUCLEOTIDE', 'FLAVIN-ADENINE DINUCLEOTIDE', 'FLAVIN-ADENINE DINUCLEOTIDE', '3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE', '3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE', '3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE', '3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE'], 'FGL2': ['CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', '1,2-ETHANEDIOL', '1,2-ETHANEDIOL', '2-AMINO-2-HYDROXYMETHYL-PROPANE-1,3-DIOL', '2-AMINO-2-HYDROXYMETHYL-PROPANE-1,3-DIOL'], 'IL18BP': [], 'NELL2': ['2-acetamido-2-deoxy-beta-D-glucopyranose', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'alpha-L-fucopyranose'], 'ADCY7': ['1-deoxy-1-[8-(dimethylamino)-7-methyl-2,

In [107]:
results_3 = pdb_parse(gene_list_3)

TRIT1
1
True
True
True
['small', 'transmembrane', 'regulator', 'of', 'ion', 'transport', '1']
7LP1
5
AC098484.3
0
TCTEX1D4
1
True
True
True
['dynein', 'light', 'chain', 'Tctex-type', '4']
1YGT
1
AL606760.1
0
AL359762.1
0
F3
1
True
True
['small', 'NF90', '(ILF3)', 'associated', 'RNA', 'A13']
2L33
0
DCLRE1B
1
True
True
True
True
True
True
['DNA', 'cross-link', 'repair', '1B']
5NZY
3
LINC00623
0
FCGR1B
1
True
True
['high', 'affinity', 'immunoglobulin', 'gamma', 'Fc', 'receptor', 'IB', 'isoform', 'X1']
1J87
12
LINC01145
0
AC245100.4
0
NBPF14
1
True
True
True
True
True
5HS6
3
C2CD4D
1
True
True
True
['C2', 'calcium', 'dependent', 'domain', 'containing', '4D']
2M3W
0
DCST2
1
True
True
True
['DC-STAMP', 'domain', 'containing', '2']
2XF4
2
SYT11
1
True
True
True
True
['synaptotagmin', '11']
1WFM
0
FCRL3
1
True
True
True
True
True
True
True
True
['Fc', 'receptor', 'like', '3']
1E4K
18
PYHIN1
1
True
True
True
['pyrin', 'and', 'HIN', 'domain', 'family', 'member', '1']
2DBG
0
CADM3
1
True
True
Tru

In [108]:
print (results_3[0])

{'TRIT1': ['NITRATE ION', 'NITRATE ION', 'NITRATE ION', 'GLYCEROL', 'GLYCEROL'], 'AC098484.3': [], 'TCTEX1D4': ['SULFATE ION'], 'AL606760.1': [], 'AL359762.1': [], 'F3': [], 'DCLRE1B': ['NICKEL (II) ION', '(6R,7R)-3-(acetyloxymethyl)-7-[[(2Z)-2-(2-amino-1,3-thiazol-4-yl)-2-methoxyimino-ethanoyl]amino]-8-oxo-5-thia-1-azabicy\\nclo[4.2.0]oct-2-ene-2-carboxylic acid', '(6R,7R)-3-(acetyloxymethyl)-7-[[(2Z)-2-(2-amino-1,3-thiazol-4-yl)-2-methoxyimino-ethanoyl]amino]-8-oxo-5-thia-1-azabicy\\nclo[4.2.0]oct-2-ene-2-carboxylic acid'], 'LINC00623': [], 'FCGR1B': ['2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-D-mannopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'alpha-L-fucop

In [109]:
results_4 = pdb_parse(gene_list_4)

IL21-AS1
0
DDX60
1
True
True
['DExD/H-box', 'helicase', '60']
2VL7
1
DDX60L
1
True
True
['DExD/H-box', '60', 'like']
2VL7
1
AC008581.1
0
SCAMP1-AS1
0
AC113382.2
0
AC106795.5
0
AL021328.1
0
HLA-L
1
True
4W8R
0
NCR3
1
True
True
True
True
True
True
True
['natural', 'cytotoxicity', 'triggering', 'receptor', '3']
3NOI
10
MYMX
1
True
True
True
True
True
True
['myoblast', 'fusion', 'factor']
1MDY
0
HMGCLL1
1
True
True
True
True
True
['3-hydroxy-3-methylglutaryl-CoA', 'lyase', 'like', '1']
1TXT
4
TPBG
1
True
True
['trophoblast', 'glycoprotein', 'like']
4CNC
32
SCML4
1
True
True
True
['Scm', 'polycomb', 'group', 'protein', 'like', '4']
5J8Y
0
FUCA2
1
True
True
True
['alpha-L-fucosidase', '2']
1HL9
2
RAET1G
1
True
True
True
['retinoic', 'acid', 'early', 'transcript', '1G']
1JFM
0
AC004847.1
0
IGFBP1
1
True
True
True
True
True
['cellular', 'communication', 'network', 'factor', '1']
4G4F
0
SGCE
1
True
True
True
True
True
['sarcoglycan', 'epsilon']
6XG7
2
TRIM56
1
True
True
True
['tripartite', 'mot

In [111]:
print (results_4[0])

{'IL21-AS1': [], 'DDX60': ['PHOSPHATE ION'], 'DDX60L': ['PHOSPHATE ION'], 'AC008581.1': [], 'SCAMP1-AS1': [], 'AC113382.2': [], 'AC106795.5': [], 'AL021328.1': [], 'HLA-L': [], 'NCR3': ['CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', 'CALCIUM ION', '2-(2-{2-[2-(2-METHOXY-ETHOXY)-ETHOXY]-ETHOXY}-ETHOXY)-ETHANOL', '2-(2-{2-[2-(2-METHOXY-ETHOXY)-ETHOXY]-ETHOXY}-ETHOXY)-ETHANOL', '2-(2-{2-[2-(2-METHOXY-ETHOXY)-ETHOXY]-ETHOXY}-ETHOXY)-ETHANOL'], 'MYMX': [], 'HMGCLL1': ['ACETOACETYL-COENZYME A', 'ACETOACETYL-COENZYME A', 'ACETOACETYL-COENZYME A', 'ACETOACETYL-COENZYME A'], 'TPBG': ['2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'DI(HYDROXYETHYL)ETHER', 'DI(HYDROXYETHYL)ETHER', 'DI(HYDROXYETHYL)ETHER', 'DI(HYDROXYETHYL)ETHER', 'GLYCEROL',

In [112]:
results_5 = pdb_parse(gene_list_5)

C11orf74
1
True
True
True
True
True
['intraflagellar', 'transport', 'associated', 'protein']
4UZY
2
OR5B1P
0
FAM111B
1
True
True
True
True
['FAM111', 'trypsin', 'like', 'peptidase', 'B']
1AQ7
0
FAM111A
1
True
True
True
True
['FAM111', 'trypsin', 'like', 'peptidase', 'A']
1EPT
1
GAL
1
True
True
True
True
True
['collagen', 'beta(1-O)galactosyltransferase', '1']
6TEX
10
AP001646.2
0
PIWIL4
1
True
True
True
True
['piwi', 'like', 'RNA-mediated', 'gene', 'silencing', '4']
2NUB
0
TMEM136
1
True
True
True
['TLC', 'domain', 'containing', '5']
1EI4
2
LPAR5
1
True
True
True
True
True
True
['lysophosphatidic', 'acid', 'receptor', '5']
7YU4
1
ACRBP
1
True
True
True
True
True
['acrosin', 'binding', 'protein']
1FIZ
9
AC125611.3
0
TROAP
1
True
True
True
['trophinin', 'associated', 'protein']
4XTK
0
HOTAIR
0
DCN
1
True
True
True
True
True
['defective', 'in', 'cullin', 'neddylation', '1', 'domain', 'containing', '3']
2L4E
0
AC069209.1
0
LINC00943
0
LINC01257
0
LRRC63
1
True
True
['leucine', 'rich', 'rep

In [113]:
print (results_5[0])

{'C11orf74': ['CITRATE ANION', 'MALONATE ION'], 'OR5B1P': [], 'FAM111B': [], 'FAM111A': ['CALCIUM ION'], 'GAL': ['GLYCEROL', 'GLYCEROL', '2-OXOGLUTARIC ACID', "URIDINE-5'-DIPHOSPHATE", 'FE (II) ION', 'FE (II) ION', 'MANGANESE (II) ION', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose'], 'AP001646.2': [], 'PIWIL4': [], 'TMEM136': ['MAGNESIUM ION', 'SPERMINE'], 'LPAR5': ['[(2~{R})-2-[5-(2-hexylphenyl)pentanoylamino]-3-oxidanyl-propyl] dihydrogen phosphate'], 'ACRBP': ['SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'P-AMINO BENZAMIDINE', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-alpha-D-glucopyranose', 'beta-D-mannopyranose', 'beta-L-fucopyranose'], 'AC125611.3': [], 'TROAP': [], 'HOTAIR': [], 'DCN': [], 'AC069209.1': [], 'LINC00943': [], 'LINC01257': [], 'LRRC63': ['BROMIDE ION'], 'GPR18': ['8-[(2E)-3-(4-chlorophenyl)prop-2-enoyl]-3-[(3,4-dichlorophenyl)methyl]-1-oxa-3,8-

In [114]:
results_6 = pdb_parse(gene_list_6)

PDE6G
1
True
True
True
True
['phosphodiesterase', '6G']
2V3L
1
LAMA1
1
True
True
True
True
True
['laminin', 'subunit', 'alpha', '1']
5IK5
17
HMSD
1
True
True
True
True
True
True
['histocompatibility', 'minor', 'serpin', 'domain', 'containing']
3CVH
0
FAM69C
1
True
True
True
True
True
['divergent', 'protein', 'kinase', 'domain', '1C']
2M8U
0
FSD1
1
True
True
True
True
True
['major', 'facilitator', 'superfamily', 'domain', 'containing', '12']
6KKJ
2
TNFSF14
1
True
True
True
True
True
True
['TNF', 'superfamily', 'member', '14']
4RSU
27
AC011511.4
0
AC114271.1
0
S1PR5
1
True
True
True
True
True
True
True
['sphingosine-1-phosphate', 'receptor', '5']
7YXA
9
ZNF433-AS1
0
ASF1B
1
True
True
True
['anti-silencing', 'function', '1B', 'histone', 'chaperone']
2Z3F
0
TM6SF2
1
True
True
['transmembrane', '6', 'superfamily', 'member', '2']
7TX6
2
AC011477.1
0
ZNF90
1
True
True
True
True
True
['HIC', 'ZBTB', 'transcriptional', 'repressor', '1']
4Y3J
15
BNIP3P17
0
IPO5P1
0
TSHZ3
1
True
True
True
True
['

In [115]:
print (results_6[0])

{'PDE6G': ['RHODAMINE 6G'], 'LAMA1': ['CALCIUM ION', 'CALCIUM ION', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', '7-hydroxy-4-methyl-2H-chromen-2-one', '2-acetamido-2-deoxy-alpha-D-galactopyranose', 'beta-D-galactopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-glucopyranuronic acid', 'alpha-D-xylopyranose', 'beta-D-glucopyranuronic acid', 'alpha-D-xylopyranose'], 'HMSD': [], 'FAM69C': [], 'FSD1': ['nonyl beta-D-glucopyranoside', 'nonyl beta-D-glucopyranoside'], 'TNFSF14': ['CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'CHLORIDE ION', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D

In [118]:
results_1[0].update(results_2[0])

In [120]:
results_1[0].update(results_3[0])

In [121]:
results_1[0].update(results_4[0])

In [122]:
results_1[0].update(results_5[0])

In [123]:
results_1[0].update(results_6[0])

In [136]:

np.save('my_dict.npy', results_1[0]) 

dict_values([['ZINC ION', 'ZINC ION', 'ZINC ION', "ADENOSINE-5'-DIPHOSPHATE", "ADENOSINE-5'-DIPHOSPHATE", "ADENOSINE-5'-DIPHOSPHATE", 'TETRAFLUOROALUMINATE ION', 'TETRAFLUOROALUMINATE ION', 'TETRAFLUOROALUMINATE ION', 'MAGNESIUM ION', 'MAGNESIUM ION', 'MAGNESIUM ION'], ['ZINC ION', 'ZINC ION', 'ZINC ION', 'ZINC ION'], [], [], [], ["URIDINE-5'-DIPHOSPHATE", "URIDINE-5'-DIPHOSPHATE", 'MAGNESIUM ION', 'MAGNESIUM ION', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'CHLORIDE ION', 'CHLORIDE ION', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-D-mannopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-D-mannopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '

In [126]:
results_1[1].extend(results_2[1])

In [128]:
results_1[1].extend(results_3[1])

In [129]:
results_1[1].extend(results_4[1])

In [130]:
results_1[1].extend(results_5[1])

In [131]:
results_1[1].extend(results_6[1])

In [132]:
print (len(results_1[1]))

108


In [133]:
df_questionable = pd.DataFrame(data={'Questionable_Genes':results_1[1]})

In [134]:
df_questionable.to_csv('need_to_confirm_values')

In [10]:
read_dictionary = np.load('my_dict.npy',allow_pickle='TRUE').item()

In [23]:
set_values_1 = [v for k,v in read_dictionary.items()]

In [27]:
set_values_2 = []
for x in set_values_1:
    for y in x:
        set_values_2.append(y)

In [39]:
set_values_2 = set(set_values_2)
set_values_2 = list(set_values_2)

In [40]:
series_rep = pd.Series(set_values_2)

In [63]:
print (series_rep[80:])

80                                       N-OXALYLGLYCINE
81          PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER
82                          beta-D-glucopyranuronic acid
83                                  alpha-L-fucopyranose
84                                           SULFATE ION
85                                           ACETATE ION
86              2-acetamido-2-deoxy-beta-D-glucopyranose
87     N-{3-[(5R)-3-amino-2,5-dimethyl-1,1-dioxido-5,...
88                                  beta-D-glucopyranose
89                                       COPPER (II) ION
90                                     ISOPROPYL ALCOHOL
91                                   NONAETHYLENE GLYCOL
92                                 FLAVIN MONONUCLEOTIDE
93                        URIDINE-5'-DIPHOSPHATE-GLUCOSE
94     (~{Z})-7-[(1~{R},2~{R},3~{R},5~{S})-2-[(~{E},3...
95                                            OLEIC ACID
96                                beta-D-galactopyranose
97                             

In [80]:
print (series_rep[129])

N-(3-{5-[5-(1H-INDOL-4-YL)-1,3,4-OXADIAZOL-2-YL]-3-(TRIFLUOROMETHYL)-1H-PYRAZOL-1-YL}BENZYL)-L-ALANINAMIDE


In [ ]:
vitamin_a = []
vitamin_c = ['GLUTATHIONE']
vitamin_d = []
vitamin_e = []
vitamin_k = []
vitamin_b6 = []
vitamin_b12 = ['S-ADENOSYL-L-HOMOCYSTEINE','S-ADENOSYLMETHIONINE','4-METHYL-HISTIDINE']
iron = ['FE (II) ION','PROTOPORPHYRIN IX CONTAINING FE','FE (III) ION']
calcium = ['CALCIUM ION']
selenium = ['GLUTATHIONE']
iodine = []
thiamin = ['(2R)-2,3-dihydroxypropyl (9Z)-octadec-9-enoate','TAUROCHOLIC ACID','CHOLESTEROL','ACETOACETYL-COENZYME A','(3beta,14beta,17beta,25R)-3-[4-methoxy-3-(methoxymethyl)butoxy]spirost-5-en','3-[(3-CHOLAMIDOPROPYL)DIMETHYLAMMONIO]-1-PROPANESULFONATE','O-[(R)-{[(2R)-2,3-bis(octadecanoyloxy)propyl]oxy}(hydroxy)phosphoryl]-L-serine','MYRISTIC ACID',"OLEIC ACID",'(1R)-2-{[(S)-{[(2S)-2,3-dihydroxypropyl]oxy}(hydroxy)phosphoryl]oxy}-1-[(hexadecanoyloxy)methyl]ethyl\n(9Z)-octadec-9-enoate',"(Z)-7-[(1R,2R,3R)-3-hydroxy-2-[(E,3S)-3-hydroxyoct-1-enyl]-5-oxo-cyclopentyl]hept-5-enoic acid","(9beta,13alpha)-3-hydroxyestra-1,3,5(10)-trien-17-one","PROGESTERONE"]
riboflavin = ['FLAVIN MONONUCLEOTIDE','FLAVIN-ADENINE DINUCLEOTIDE','GLUTATHIONE', 'NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE',"GUANOSINE-5'-TRIPHOSPHATE","S-ADENOSYL-L-HOMOCYSTEINE","URIDINE-5'-DIPHOSPHATE","S-ADENOSYLMETHIONINE","ADENOSINE-5'-DIPHOSPHATE","3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE","ADENOSINE-3'-5'-DIPHOSPHATE","5-AMINO-1H-PYRIMIDINE-2,4-DIONE","NICOTINAMIDE-ADENINE-DINUCLEOTIDE","D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER",'FLAVIN MONONUCLEOTIDE',"URIDINE-5'-DIPHOSPHATE-GLUCOSE","1-deoxy-1-[8-(dimethylamino)-7-methyl-2,4-dioxo-3,4-dihydrobenzo[g]pteridin-10(2H)-yl]-D-ribitol","GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER","NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
niacin = ['NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE','NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE','NICOTINAMIDE-ADENINE-DINUCLEOTIDE',"GUANOSINE-5'-TRIPHOSPHATE","S-ADENOSYL-L-HOMOCYSTEINE",'FLAVIN-ADENINE DINUCLEOTIDE',"URIDINE-5'-DIPHOSPHATE","S-ADENOSYLMETHIONINE","ADENOSINE-5'-DIPHOSPHATE","3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE","ADENOSINE-3'-5'-DIPHOSPHATE","5-AMINO-1H-PYRIMIDINE-2,4-DIONE","D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER","URIDINE-5'-DIPHOSPHATE-GLUCOSE","GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER","NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
folate = ['S-ADENOSYL-L-HOMOCYSTEINE','S-ADENOSYLMETHIONINE','NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE',"GUANOSINE-5'-TRIPHOSPHATE","S-ADENOSYL-L-HOMOCYSTEINE",'FLAVIN-ADENINE DINUCLEOTIDE',"URIDINE-5'-DIPHOSPHATE","S-ADENOSYLMETHIONINE","ADENOSINE-5'-DIPHOSPHATE","3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE","ADENOSINE-3'-5'-DIPHOSPHATE","5-AMINO-1H-PYRIMIDINE-2,4-DIONE","NICOTINAMIDE-ADENINE-DINUCLEOTIDE","D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER","URIDINE-5'-DIPHOSPHATE-GLUCOSE","GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER",'4-METHYL-HISTIDINE',"NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
biotin = []
pantothenic_acid = ['(2R)-2,3-dihydroxypropyl (9Z)-octadec-9-enoate','TAUROCHOLIC ACID','CHOLESTEROL','ACETOACETYL-COENZYME A','(3beta,14beta,17beta,25R)-3-[4-methoxy-3-(methoxymethyl)butoxy]spirost-5-en','3-[(3-CHOLAMIDOPROPYL)DIMETHYLAMMONIO]-1-PROPANESULFONATE','O-[(R)-{[(2R)-2,3-bis(octadecanoyloxy)propyl]oxy}(hydroxy)phosphoryl]-L-serine','MYRISTIC ACID',"OLEIC ACID",'(1R)-2-{[(S)-{[(2S)-2,3-dihydroxypropyl]oxy}(hydroxy)phosphoryl]oxy}-1-[(hexadecanoyloxy)methyl]ethyl\n(9Z)-octadec-9-enoate',"(Z)-7-[(1R,2R,3R)-3-hydroxy-2-[(E,3S)-3-hydroxyoct-1-enyl]-5-oxo-cyclopentyl]hept-5-enoic acid","(9beta,13alpha)-3-hydroxyestra-1,3,5(10)-trien-17-one","PROGESTERONE"]
phosphorous = ['PHOSPHATE ION', "ADENOSINE-5'-TRIPHOSPHATE","GUANOSINE-5'-TRIPHOSPHATE",'PHOSPHATIDYLETHANOLAMINE',"URIDINE-5'-DIPHOSPHATE",'NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE','NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE',"ADENOSINE-5'-DIPHOSPHATE",'3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE','ADENOSINE-3'-5'-DIPHOSPHATE','PHOSPHATE ION','D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE',"NICOTINAMIDE-ADENINE-DINUCLEOTIDE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER","FLAVIN MONONUCLEOTIDE","URIDINE-5'-DIPHOSPHATE-GLUCOSE","GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER",'3-METHYLBUT-3-ENYL TRIHYDROGEN DIPHOSPHATE',"NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
magnesium = ['MAGNESIUM ION','GLUTATHIONE']
zinc = ['ZINC ION']
copper = ['COPPER (II) ION']
manganese = ['MANGANESE (II) ION']
chromium = []
molybdenum = []
chloride = ['CHLORIDE ION']
potassium = []
choline = ['PHOSPHATIDYLETHANOLAMINE']

Some notes:
Vitamin B12 (cyanocobalamin) and folate are being tethered with SAM and its unmethylated counterpart (SAM+) because they replenish the missing methyl group.  Thus they are involved in methylation reactions in general.

Any fatty acids/cholesterols involved panthothenic acid and CoA formation to form 
https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/fatty-acid-synthesis#:~:text=Fatty%20acid%20synthesis%20is%20a,Sasaki%20and%20Nagano%2C%202004).
https://www.sciencedirect.com/topics/medicine-and-dentistry/cholesterol-synthesis.

Thiamin works hand in hand with pantothenic acid (transfer of 2 carbon... Acetyl groups), so will go with pantothenic labels.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5347104/#:~:text=Specifically%2C%20thiamin%20pyrophosphate%20(TPP),%2Dketoglutarate%20to%20succinyl%2DCoA.


Anything with phosphate will go into phosphorous group (phosphate = PO4).

Glutathione is major player when it comes to redox balance in body, so it will be connected with many enzymes and consequently nutrients.  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6770193/

Nitrogenous base synthesis:
purines and pyrimidines: Folate, phosphorous, riboflavin, niacin
https://med.libretexts.org/Bookshelves/Basic_Science/Cell_Biology_Genetics_and_Biochemistry_for_Pre-Clinical_Students/07%3A_Pentose_phosphate_pathway_(PPP)_purine_and_pyrimidine_metabolism/7.02%3A_Nucleotide_Synthesis

Lets run through the questionable queries and see if we can extract some more information
:

In [81]:
df_0 = pd.read_csv('need_to_confirm_values')

In [83]:
df_0 = df_0.drop(columns='Unnamed: 0')


In [105]:
df_0.shape

(108, 1)

In [104]:
df_0['Questionable_Genes'].head(50)

0          MERTK
1          MGAT5
2          CASP7
3          BACE2
4            MSN
5            FAS
6            GLS
7           SELL
8       IL6R-AS1
9           LY75
10          VCAN
11         LMNB1
12        CD300E
13         SYT17
14    AL109811.2
15    AL365209.1
16    AC098484.3
17    AL606760.1
18    AL359762.1
19     LINC00623
20     LINC01145
21    AC245100.4
22         SYT11
23    AC091488.1
24     LINC01116
25    AC098820.2
26    AC104772.1
27    AC012485.3
28    AC131097.4
29    AC105749.1
30          CAMP
31       RPL32P9
32         HTRA3
33    AC104663.1
34      IL21-AS1
35    AC008581.1
36    SCAMP1-AS1
37    AC113382.2
38    AC106795.5
39    AL021328.1
40         FUCA2
41    AC004847.1
42          SGCE
43    AC099548.2
44    AC019257.7
45    AC027702.1
46    AC131902.2
47     LINC00968
48           IL7
49    AF117829.1
Name: Questionable_Genes, dtype: object

In [98]:
blank_entries = [k for k,v in read_dictionary.items() if v == []]

In [99]:
print (len(blank_entries))

163


so since there are 163 blank entries and 108 questionable entries, I figure that 53 of the genes were able to pass all the way to the PDB ligand query and just returned no ligands, but that means that 108 were either unable to pass the intial kegg search, producing no information in the initial request or the protein name was short (2 or less strings)

lets examine the questionable genes first, and then see if we can elminiate some genes for next query

1.) the entries with periods are said to be 'undergoing sequencing' at the NIH gene query, so lets drop those as they are not valid

2.) the entries starting with LINC are non protein coding sections, so they should dropped as well

3.) entries with dashes get hits when the the dashed part is removed

In [116]:
def gene_cleaner(gene_list):
    clean_list = []
    for gene in gene_list:
        if '.' in gene:
            continue
        if 'LINC' in gene:
            continue
        if '-' in gene:
            gene_split = []
            for x in gene:
                gene_split.append(x)
            end = gene_split.index('-')
            clean = gene_split[:end]
            clean_list.append(''.join(clean))
        else:
            clean_list.append(gene)
        
            
    return clean_list
            

                
            

In [119]:
gene_list_to_be_cleaned = list(df_0['Questionable_Genes'])
res = gene_cleaner(gene_list_to_be_cleaned)
print (res)

['MERTK', 'MGAT5', 'CASP7', 'BACE2', 'MSN', 'FAS', 'GLS', 'SELL', 'IL6R', 'LY75', 'VCAN', 'LMNB1', 'CD300E', 'SYT17', 'SYT11', 'CAMP', 'RPL32P9', 'HTRA3', 'IL21', 'SCAMP1', 'FUCA2', 'SGCE', 'IL7', 'CPQ', 'MAFA', 'EEF1A1P5', 'SHLD2P1', 'NPM1P25', 'OR5B1P', 'HOTAIR', 'JPH4', 'TC2N', 'IGHV4', 'IGHV3', 'GOLGA8DP', 'SPINT1', 'DRAIC', 'IL16', 'DERL2', 'E2F3P1', 'MRPL45P2', 'CD300C', 'PDE6G', 'ZNF433', 'BNIP3P17', 'IPO5P1', 'RAB4B', 'CARD8', 'FTLP3', 'ARHGAP8', 'CA5B', 'MAP2K4P1', 'SEPT6']


In [143]:
print (len(res))

53


now lets see how many of these are entries that set off the questionability alarm because of the protein name length, but were able to make a full entry in the end

In [147]:
def length_checks(gene_dic):
    length_checks = []
    res = gene_cleaner(gene_list_to_be_cleaned)
    for k,v in gene_dic.items():
        if k in res and v != []:
            length_checks.append(k)
            
    return length_checks

In [148]:
length_checks = length_checks(read_dictionary)
print (length_checks)

['MGAT5', 'BACE2', 'MSN', 'FAS', 'SELL', 'VCAN', 'CAMP', 'RPL32P9', 'FUCA2', 'SGCE', 'IL7', 'CPQ', 'EEF1A1P5', 'OR5B1P', 'JPH4', 'SPINT1', 'PDE6G', 'FTLP3', 'ARHGAP8', 'SEPT6']


In [144]:
print (len(length_checks))

16


In [124]:
for x in length_checks:
    print (f'{x}:',read_dictionary[x])

MGAT5: ["URIDINE-5'-DIPHOSPHATE", "URIDINE-5'-DIPHOSPHATE", 'MAGNESIUM ION', 'MAGNESIUM ION', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'GLYCEROL', 'CHLORIDE ION', 'CHLORIDE ION', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-D-mannopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-D-mannopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-D-mannopyranose', 'alpha-L-fucopyranose']
BACE2: ['N-{3-[(5R)-3-amino-2,5-dimethyl-1,1-dioxido-5,6-dihydro-2H-1,2,4-thiadiazin-5-yl]-4-fluorophenyl}-5-fluoropyridine-2-carboxamide', 'CHLORIDE ION', '1,2-ETHANEDIOL', '1,2-ETHAN

Now time to confirm these entries

Which ones are okay: BACE2 , MSN, FAS, VCAN, CAMP, FUCA2, SGCE, IL7, CPQ, JPH4, PDE6G, SEPT6


Which ones did not go in correctly: MGAT5, SPINT1, ARHGAP8

In [125]:
correction_dict = {'MGAT5':'alpha-1,6-mannosylglycoprotein 6-beta-N-acetylglucosaminyltransferase', 'SPINT1':'serine peptidase inhibitor, Kunitz type 1', 'ARHGAP8':'Rho GTPase activating protein 8'}

In [126]:
def pdb_parse_v2(gene_dict):
    results = {}
    for k,v in gene_dict.items():
        print (k)
        
            
        q1 = TextQuery(f"{v}")

        # add parameter as a list with either "computational" or "experimental" or both as list values
        q2 = q1(return_content_type=["experimental"])

        q3 =  (list(q2))
        q4 = [x for x in q3 if len(x) == 4]
        
        print (q4[0])
        
        url = f'https://www.ebi.ac.uk/pdbe/api/pdb/entry/ligand_monomers/{q4[0]}'
        r = requests.get(url) 
        soup = bs4.BeautifulSoup(r.content, 
                                     "lxml") 
        query=soup.find_all( 'p' ) 


        comp_list = []
        start=0
        end=0

        for x in query:
            x = str(x)
            for y in range(len(x)):
                if x[y] =='c' and x[y+1]== 'h' and x[y+10] == 'n':
                        start = y + 17 
                elif start != 0 and x[y] == '"' and x[y+1] == ',':
                        end = y
                if start != 0 and end != 0:
                        comp_list.append(x[start:end])
                        start = 0
                        end= 0

        results[k] = comp_list
        print (len(comp_list)) 
        
        
    return results

In [127]:
corrections = pdb_parse_v2(correction_dict)
print (corrections)

MGAT5
6YJR
9
SPINT1
3T62
7
ARHGAP8
8K70
4
{'MGAT5': ['2-acetamido-2-deoxy-beta-D-glucopyranose', '1,2-ETHANEDIOL', '1,2-ETHANEDIOL', '1,2-ETHANEDIOL', '1,2-ETHANEDIOL', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'alpha-L-fucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'alpha-L-fucopyranose'], 'SPINT1': ['SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION'], 'ARHGAP8': ['TETRAETHYLENE GLYCOL', 'TETRAETHYLENE GLYCOL', 'TETRAETHYLENE GLYCOL', 'TETRAETHYLENE GLYCOL']}


In [128]:
key_list = [k for k,v in corrections.items()]
for k,v in read_dictionary.items():
    if k in key_list:
        print (k)
        read_dictionary[k] = corrections[k]
        


MGAT5
SPINT1
ARHGAP8


In [130]:
print (read_dictionary['MGAT5'])

['2-acetamido-2-deoxy-beta-D-glucopyranose', '1,2-ETHANEDIOL', '1,2-ETHANEDIOL', '1,2-ETHANEDIOL', '1,2-ETHANEDIOL', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'alpha-L-fucopyranose', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'alpha-L-fucopyranose']


In [131]:
print (read_dictionary['SPINT1'])

['SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION', 'SULFATE ION']


Now lets examine the entries that were empty and  got flagged because they were either small or did not pass the inital search

In [134]:
def blank_checks(gene_dic):
    blank_checks = []
    res = gene_cleaner(gene_list_to_be_cleaned)
    for k,v in gene_dic.items():
        if k in res and v == []:
            blank_checks.append(k)
            
    return blank_checks

In [135]:
blanks = blank_checks(read_dictionary)
print (blanks)

['MERTK', 'CASP7', 'GLS', 'LY75', 'LMNB1', 'CD300E', 'SYT17', 'SYT11', 'RPL32P9', 'HTRA3', 'EEF1A1P5', 'SHLD2P1', 'NPM1P25', 'OR5B1P', 'HOTAIR', 'TC2N', 'GOLGA8DP', 'DRAIC', 'IL16', 'DERL2', 'E2F3P1', 'MRPL45P2', 'CD300C', 'BNIP3P17', 'IPO5P1', 'FTLP3', 'CA5B', 'MAP2K4P1']


In [145]:
print (len(blanks))

28


Entries that were correctly blank: MERTK, CASP7, GLS, 7JPU, LMNB1, CD300E, SYT17, SYT11, HTRA3, SHLD2P1, NPM1P25, HOTAIR, TC2N, GOLGA8DP, DRAIC, IL16, DERL2, E2F3P1, MRPL45P2, CD300C, BNIP3P17, IPO5P1, CA5B, MAP2K4P1
    
Entries that were incorrectly blank: RPL32P9, EEF1A1P5, OR5B1P, FTLP3
    

In [136]:
incorrect_blank = {'RPL32P9':'ribosomal protein L32 pseudogene 9', 'EEF1A1P5':'eukaryotic translation elongation factor 1 alpha 1 pseudogene 5', 'OR5B1P':'olfactory receptor family 5 subfamily B member 1 pseudogene', 'FTLP3':'ferritin light chain pseudogene 3 '}

In [137]:
was_blank = pdb_parse_v2(incorrect_blank)

RPL32P9
1JZX
3
EEF1A1P5
6RA9
22
OR5B1P
2Q72
10
FTLP3
3H7G
16


In [138]:
key_list = [k for k,v in was_blank.items()]
for k,v in read_dictionary.items():
    if k in key_list:
        print (k)
        read_dictionary[k] = was_blank[k]

RPL32P9
EEF1A1P5
OR5B1P
FTLP3


In [140]:
print (read_dictionary['OR5B1P'])

['octyl beta-D-glucopyranoside', 'octyl beta-D-glucopyranoside', 'octyl beta-D-glucopyranoside', 'octyl beta-D-glucopyranoside', 'octyl beta-D-glucopyranoside', 'SODIUM ION', 'SODIUM ION', 'LEUCINE', '3-(5H-DIBENZO[B,F]AZEPIN-5-YL)-N,N-DIMETHYLPROPAN-1-AMINE', '3-(5H-DIBENZO[B,F]AZEPIN-5-YL)-N,N-DIMETHYLPROPAN-1-AMINE']


Now lets check the missing values that were excluded when doing the searches because their names were edited

In [149]:
length_keys = key_list
blank_keys = was_blank

In [160]:
total_set = set(res)
frac_1 = set(length_checks)
frac_2 = set(blanks)


In [161]:
print (total_set)

{'ARHGAP8', 'CD300E', 'FTLP3', 'IL16', 'CARD8', 'MAP2K4P1', 'DERL2', 'LY75', 'DRAIC', 'BNIP3P17', 'SGCE', 'RAB4B', 'TC2N', 'IGHV4', 'CASP7', 'OR5B1P', 'CAMP', 'MGAT5', 'EEF1A1P5', 'E2F3P1', 'MSN', 'JPH4', 'IGHV3', 'GLS', 'VCAN', 'HOTAIR', 'IPO5P1', 'HTRA3', 'IL6R', 'SPINT1', 'RPL32P9', 'IL21', 'GOLGA8DP', 'SELL', 'BACE2', 'MRPL45P2', 'LMNB1', 'ZNF433', 'SEPT6', 'SHLD2P1', 'SCAMP1', 'CD300C', 'NPM1P25', 'FAS', 'CPQ', 'SYT11', 'FUCA2', 'IL7', 'MERTK', 'SYT17', 'CA5B', 'MAFA', 'PDE6G'}


In [162]:
print ((total_set-frac_1)-frac_2)

{'RAB4B', 'IL6R', 'IGHV4', 'IL21', 'CARD8', 'ZNF433', 'MAFA', 'IGHV3', 'SCAMP1'}


In [174]:
for x in df_0['Questionable_Genes']:

    if '-' in x:
       print (x)

IL6R-AS1
IL21-AS1
SCAMP1-AS1
MAFA-AS1
IGHV4-59
IGHV3-72
ZNF433-AS1
RAB4B-EGLN2
CARD8-AS1


In [175]:
full_name = ['RAB4B-EGLN2','IL6R-AS1','IGHV4-59','IL21-AS1','CARD8-AS1','ZNF433-AS1','MAFA-AS1','IGHV3-72','SCAMP1-AS1']

In [165]:
gene_list_not_hyph = list(((total_set-frac_1)-frac_2))

In [168]:
no_longer_hyphenated = pdb_parse(gene_list_not_hyph)
print (no_longer_hyphenated)

RAB4B
1
True
True
True
['member', 'RAS', 'oncogene', 'family']
1Z0F
2
IL6R
1
True
True
True
True
True
True
True
True
True
True
True
True
True
['interleukin', '6', 'receptor']
1I1R
0
IGHV4
1
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
['immunoglobulin', 'heavy', 'variable', '4-38-2-like']
1RZ7
2
IL21
1
True
True
True
True
True
['interleukin', '21', 'receptor']
4W8G
0
CARD8
1
True
True
True
True
True
True
True
True
['caspase', 'recruitment', 'domain', 'family', 'member', '8']
3CRD
0
ZNF433
1
True
True
['zinc', 'finger', 'protein', '433']
2CTD
2
MAFA
1
True
True
True
True
True
['MAF', 'bZIP', 'transcription', 'factor', 'A']
3A5T
1
IGHV3
0
SCAMP1
1
True
True
True
True
['secretory', 'carrier', 'membrane', 'protein', '1']
6FUT
2
({'RAB4B': ['MAGNESIUM ION', "GUANOSINE-5'-DIPHOSPHATE"], 'IL6R': [], 'IGHV4': ['GLYCEROL', 'GLYCEROL'], 'IL21': [], 'CARD8': [], 'ZNF433': ['ZINC ION', 'ZINC ION'], 'MAFA': ['MAGNESIUM ION'], 'IGHV3': [], 'SCAMP1': ['3-[3-(aminomethyl)

In [178]:
no_hyphen_values = [v for k,v in no_longer_hyphenated[0].items()]
no_hyphen_dict = {}
for x in range(len(full_name)):
    no_hyphen_dict[full_name[x]] = no_hyphen_values[x]

In [179]:
print (no_hyphen_dict)

{'RAB4B-EGLN2': ['MAGNESIUM ION', "GUANOSINE-5'-DIPHOSPHATE"], 'IL6R-AS1': [], 'IGHV4-59': ['GLYCEROL', 'GLYCEROL'], 'IL21-AS1': [], 'CARD8-AS1': [], 'ZNF433-AS1': ['ZINC ION', 'ZINC ION'], 'MAFA-AS1': ['MAGNESIUM ION'], 'IGHV3-72': [], 'SCAMP1-AS1': ['3-[3-(aminomethyl)phenyl]-~{N}-[(1~{S})-1,2,3,4-tetrahydronaphthalen-1-yl]benzamide', 'SUCCINIC ACID']}


In [181]:
no_hyphen_keys = [k for k,v in no_hyphen_dict.items()]
for k,v in read_dictionary.items():
    if k in no_hyphen_keys:
        print (k)
        read_dictionary[k] = no_hyphen_dict[k]

IL6R-AS1
IL21-AS1
SCAMP1-AS1
MAFA-AS1
IGHV4-59
IGHV3-72
ZNF433-AS1
RAB4B-EGLN2
CARD8-AS1


In [184]:
print (read_dictionary['IGHV3-72'])

[]


In [185]:
np.save('corrected_dict.npy', read_dictionary) 

In [3]:
corr_dict = np.load('corrected_dict.npy',allow_pickle='TRUE').item()

In [4]:
blank_list = [k for k,v in corr_dict.items() if v == []]

In [5]:
print(len(blank_list))

154


In [6]:
print ('the amount of data points we have is:', 307-154)

the amount of data points we have is: 153


And the amount of vitamins we have labelled to ligands is 17/27 with a heavy skew towards riboflavin, niacin, phosphorous, pantothenic acid, thiamin

In [ ]:
vitamin_a = []
vitamin_c = ['GLUTATHIONE']
vitamin_d = []
vitamin_e = []
vitamin_k = []
vitamin_b6 = []
vitamin_b12 = ['S-ADENOSYL-L-HOMOCYSTEINE','S-ADENOSYLMETHIONINE','4-METHYL-HISTIDINE']
iron = ['FE (II) ION','PROTOPORPHYRIN IX CONTAINING FE','FE (III) ION']
calcium = ['CALCIUM ION']
selenium = ['GLUTATHIONE']
iodine = []
thiamin = ['(2R)-2,3-dihydroxypropyl (9Z)-octadec-9-enoate','TAUROCHOLIC ACID','CHOLESTEROL','ACETOACETYL-COENZYME A','(3beta,14beta,17beta,25R)-3-[4-methoxy-3-(methoxymethyl)butoxy]spirost-5-en','3-[(3-CHOLAMIDOPROPYL)DIMETHYLAMMONIO]-1-PROPANESULFONATE','O-[(R)-{[(2R)-2,3-bis(octadecanoyloxy)propyl]oxy}(hydroxy)phosphoryl]-L-serine','MYRISTIC ACID',"OLEIC ACID",'(1R)-2-{[(S)-{[(2S)-2,3-dihydroxypropyl]oxy}(hydroxy)phosphoryl]oxy}-1-[(hexadecanoyloxy)methyl]ethyl\n(9Z)-octadec-9-enoate',"(Z)-7-[(1R,2R,3R)-3-hydroxy-2-[(E,3S)-3-hydroxyoct-1-enyl]-5-oxo-cyclopentyl]hept-5-enoic acid","(9beta,13alpha)-3-hydroxyestra-1,3,5(10)-trien-17-one","PROGESTERONE"]
riboflavin = ['FLAVIN MONONUCLEOTIDE','FLAVIN-ADENINE DINUCLEOTIDE','GLUTATHIONE', 'NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE',"GUANOSINE-5'-TRIPHOSPHATE","S-ADENOSYL-L-HOMOCYSTEINE","URIDINE-5'-DIPHOSPHATE","S-ADENOSYLMETHIONINE","ADENOSINE-5'-DIPHOSPHATE","3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE","ADENOSINE-3'-5'-DIPHOSPHATE","5-AMINO-1H-PYRIMIDINE-2,4-DIONE","NICOTINAMIDE-ADENINE-DINUCLEOTIDE","D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER",'FLAVIN MONONUCLEOTIDE',"URIDINE-5'-DIPHOSPHATE-GLUCOSE","1-deoxy-1-[8-(dimethylamino)-7-methyl-2,4-dioxo-3,4-dihydrobenzo[g]pteridin-10(2H)-yl]-D-ribitol","GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER","NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
niacin = ['NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE','NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE','NICOTINAMIDE-ADENINE-DINUCLEOTIDE',"GUANOSINE-5'-TRIPHOSPHATE","S-ADENOSYL-L-HOMOCYSTEINE",'FLAVIN-ADENINE DINUCLEOTIDE',"URIDINE-5'-DIPHOSPHATE","S-ADENOSYLMETHIONINE","ADENOSINE-5'-DIPHOSPHATE","3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE","ADENOSINE-3'-5'-DIPHOSPHATE","5-AMINO-1H-PYRIMIDINE-2,4-DIONE","D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER","URIDINE-5'-DIPHOSPHATE-GLUCOSE","GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER","NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
folate = ['S-ADENOSYL-L-HOMOCYSTEINE','S-ADENOSYLMETHIONINE','NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE',"GUANOSINE-5'-TRIPHOSPHATE","S-ADENOSYL-L-HOMOCYSTEINE",'FLAVIN-ADENINE DINUCLEOTIDE',"URIDINE-5'-DIPHOSPHATE","S-ADENOSYLMETHIONINE","ADENOSINE-5'-DIPHOSPHATE","3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE","ADENOSINE-3'-5'-DIPHOSPHATE","5-AMINO-1H-PYRIMIDINE-2,4-DIONE","NICOTINAMIDE-ADENINE-DINUCLEOTIDE","D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER","URIDINE-5'-DIPHOSPHATE-GLUCOSE","GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER",'4-METHYL-HISTIDINE',"NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
biotin = []
pantothenic_acid = ['(2R)-2,3-dihydroxypropyl (9Z)-octadec-9-enoate','TAUROCHOLIC ACID','CHOLESTEROL','ACETOACETYL-COENZYME A','(3beta,14beta,17beta,25R)-3-[4-methoxy-3-(methoxymethyl)butoxy]spirost-5-en','3-[(3-CHOLAMIDOPROPYL)DIMETHYLAMMONIO]-1-PROPANESULFONATE','O-[(R)-{[(2R)-2,3-bis(octadecanoyloxy)propyl]oxy}(hydroxy)phosphoryl]-L-serine','MYRISTIC ACID',"OLEIC ACID",'(1R)-2-{[(S)-{[(2S)-2,3-dihydroxypropyl]oxy}(hydroxy)phosphoryl]oxy}-1-[(hexadecanoyloxy)methyl]ethyl\n(9Z)-octadec-9-enoate',"(Z)-7-[(1R,2R,3R)-3-hydroxy-2-[(E,3S)-3-hydroxyoct-1-enyl]-5-oxo-cyclopentyl]hept-5-enoic acid","(9beta,13alpha)-3-hydroxyestra-1,3,5(10)-trien-17-one","PROGESTERONE"]
phosphorous = ['PHOSPHATE ION', "ADENOSINE-5'-TRIPHOSPHATE","GUANOSINE-5'-TRIPHOSPHATE",'PHOSPHATIDYLETHANOLAMINE',"URIDINE-5'-DIPHOSPHATE",'NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE','NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE',"ADENOSINE-5'-DIPHOSPHATE",'3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE','ADENOSINE-3'-5'-DIPHOSPHATE','PHOSPHATE ION','D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE',"NICOTINAMIDE-ADENINE-DINUCLEOTIDE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER","FLAVIN MONONUCLEOTIDE","URIDINE-5'-DIPHOSPHATE-GLUCOSE","GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-TRIPHOSPHATE","PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER",'3-METHYLBUT-3-ENYL TRIHYDROGEN DIPHOSPHATE',"NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
magnesium = ['MAGNESIUM ION','GLUTATHIONE']
zinc = ['ZINC ION']
copper = ['COPPER (II) ION']
manganese = ['MANGANESE (II) ION']
chromium = []
molybdenum = []
chloride = ['CHLORIDE ION']
potassium = []
choline = ['PHOSPHATIDYLETHANOLAMINE']

In [7]:
nutrient_list = [v for k,v in corr_dict.items() if v != []]

In [9]:
print (len(nutrient_list))

153


In [21]:
individual_nutr =[]
for x in nutrient_list:
    
    for y in x:
        individual_nutr.append(y)


In [22]:
nutr_set = set(individual_nutr)

In [23]:
print (len(nutr_set))

139


In [25]:
nutr_list = list(nutr_set)

In [27]:
nutr_ser = pd.Series(nutr_list)

In [65]:
print (nutr_ser[120:])

120                                          RESVERATROL
121                                           OLEIC ACID
122                                          CLINDAMYCIN
123                      3,5,3',5'-TETRAIODO-L-THYRONINE
124    3-[(3,4-dichlorobenzyl)sulfanyl]-N-(methylsulf...
125    N-(3-{5-[5-(1H-INDOL-4-YL)-1,3,4-OXADIAZOL-2-Y...
126                                         PENICILLIN G
127                                        MAGNESIUM ION
128                                          CHOLESTEROL
129     NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE
130                                             ZINC ION
131                               URIDINE-5'-DIPHOSPHATE
132                             ADENOSINE-5'-DIPHOSPHATE
133                             GUANOSINE-5'-DIPHOSPHATE
134                                          GOLD 3+ ION
135                 2-deoxy-2-fluoro-beta-L-fucopyranose
136    N-(tert-butylsulfonyl)-4-fluoro-2-{(3S,4R)-4-h...
137                            

In [68]:
print (nutr_ser[136])

N-(tert-butylsulfonyl)-4-fluoro-2-{(3S,4R)-4-hydroxy-3-[(pyridin-2-yl)methyl]-3,4-dihydro-2H-1-benzopyran-7-yl}benzamide


In [72]:
vitamin_a = []
vitamin_c = []
vitamin_d = []
vitamin_e = []
vitamin_k = []
vitamin_b6 = []
vitamin_b12 = ['COBALT (II) ION']
iron = ['FE (III) ION',"PROTOPORPHYRIN IX CONTAINING FE","FE (II) ION"]
calcium = ['CALCIUM ION']
selenium = []
iodine = ["3,5,3',5'-TETRAIODO-L-THYRONINE"]
thiamin = []
niacin = ["NADP NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE",'NICOTINAMIDE-ADENINE-DINUCLEOTIDE',"NADPH DIHYDRO-NICOTINAMIDE-ADENINE-DINUCLEOTIDE PHOSPHATE","1,4-DIHYDRONICOTINAMIDE ADENINE DINUCLEOTIDE"]
riboflavin = ['FLAVIN-ADENINE DINUCLEOTIDE',"FLAVIN MONONUCLEOTIDE"]
folate = []
biotin = []
pantothenic_acid = ['ACETOACETYL-COENZYME A']
phosphorus = ['PHOSPHATE ION']
magnesium = []
zinc = ['ZINC ION']
copper = ['COPPER (II) ION']
manganese = ['MANGANESE (II) ION']
chromium = []
molybdenum = []
chloride = ['CHLORIDE ION']
potassium = []
choline = ['L-ALPHA-GLYCEROPHOSPHORYLETHANOLAMINE']

There has got to be a way to organize these non - explicit nutrient ligands into their general macromolecule class and then transfer that class to the appropriate nutrients that are involved in its metabolism

In [69]:
nuc = ["GUANOSINE-5'-DIPHOSPHATE","ADENOSINE-5'-DIPHOSPHATE","URIDINE-5'-DIPHOSPHATE","URIDINE-5'-DIPHOSPHATE-GLUCOSE","GUANIDINE","5-AMINO-1H-PYRIMIDINE-2,4-DIONE","ADENOSINE-3'-5'-DIPHOSPHATE","S-ADENOSYLMETHIONINE","METHOTREXATE","PHOSPHOMETHYLPHOSPHONIC ACID ADENYLATE ESTER",'S-ADENOSYL-L-HOMOCYSTEINE',"GUANOSINE-5'-TRIPHOSPHATE",'1-{4-amino-2-[(ethylamino)methyl]-1H-imidazo[4,5-c]quinolin-1-yl}-2-methylpropan-2-ol','PHOSPHOMETHYLPHOSPHONIC ACID GUANYLATE ESTER','3-AMINOPYRIDINE-ADENINE DINUCLEOTIDE PHOSPHATE','2-(3-chlorophenoxy)-3-methoxy-4-{(1R)-1-[(3S)-3-(5-methyl-2,4-dioxo-3,4-dihydropyrimidin-1(2H)-yl)piperidin-1-yl]propyl}benzoic acid','1-deoxy-1-[8-(dimethylamino)-7-methyl-2,4-dioxo-3,4-dihydrobenzo[g]pteridin-10(2H)-yl]-D-ribitol',"ADENOSINE-5'-TRIPHOSPHATE"]
sac = ["2-deoxy-2-fluoro-beta-L-fucopyranose","2-acetamido-2-deoxy-alpha-D-galactopyranose","methyl 2-acetamido-3-O-[(1R)-1-carboxyethyl]-2-deoxy-beta-D-glucopyranoside","2-deoxy-6-O-sulfo-2-(sulfoamino)-alpha-D-glucopyranose","URIDINE-5'-DIPHOSPHATE-GLUCOSE","alpha-D-xylopyranose","PHOSPHATIDYLETHANOLAMINE","alpha-D-glucopyranose","octyl beta-D-glucopyranoside","alpha-D-mannopyranose","CITRATE ANION","2-O-sulfo-alpha-L-idopyranuronic acid","beta-D-galactopyranose","2-OXOGLUTARIC ACID","alpha-L-fucopyranose","nonyl beta-D-glucopyranoside","beta-L-fucopyranose","L-ALPHA-GLYCEROPHOSPHORYLETHANOLAMINE","2-acetamido-2-deoxy-beta-D-glucopyranose","beta-D-mannopyranose","beta-D-fructofuranose","2-AMINO-2-HYDROXYMETHYL-PROPANE-1,3-DIOL","D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE","ETHANOL","beta-D-glucopyranose",'CITRIC ACID','GLYCEROL','beta-D-glucopyranuronic acid','alpha-D-galactopyranose','1,3-PROPANDIOL','SUCCINIC ACID',' 2-acetamido-2-deoxy-alpha-D-glucopyranose']
lip = ["ACETATE ION","CHOLESTEROL","OLEIC ACID","3-[(3-CHOLAMIDOPROPYL)DIMETHYLAMMONIO]-1-PROPANESULFONATE","11-(4-DIMETHYLAMINO-PHENYL)-17-HYDROXY-13-METHYL-17-PROP-1-YNYL-1,2,6,7,8,11,12,13,14,15,16,17-DODEC AHYDRO-CYCLOPENTA[A]PHENANTHREN-3-ONE","(Z)-7-[(1R,2R,3R)-3-hydroxy-2-[(E,3S)-3-hydroxyoct-1-enyl]-5-oxo-cyclopentyl]hept-5-enoic acid","octyl beta-D-glucopyranoside","(1R)-2-{[(S)-{[(2S)-2,3-dihydroxypropyl]oxy}(hydroxy)phosphoryl]oxy}-1-[(hexadecanoyloxy)methyl]ethyl\n(9Z)-octadec-9-enoate","(~{Z})-7-[(1~{R},2~{R},3~{R},5~{S})-2-[(~{E},3~{R})-4-(3-chloranylphenoxy)-3-oxidanyl-but-1-enyl]-3,5-bis(oxidanyl)cyclopentyl]hept-5-enoic acid","nonyl beta-D-glucopyranoside","(9beta,13alpha)-3-hydroxyestra-1,3,5(10)-trien-17-one","MALONATE ION","MYRISTIC ACID","TAUROCHOLIC ACID","PROGESTERONE",'GLUTATHIONE','O-[(R)-{[(2R)-2,3-bis(octadecanoyloxy)propyl]oxy}(hydroxy)phosphoryl]-L-serine','(3beta,14beta,17beta,25R)-3-[4-methoxy-3-(methoxymethyl)butoxy]spirost-5-en','3-METHYLBUT-3-ENYL TRIHYDROGEN DIPHOSPHATE','[(2~{R})-2-[5-(2-hexylphenyl)pentanoylamino]-3-oxidanyl-propyl] dihydrogen phosphate','(2R)-2,3-dihydroxypropyl (9Z)-octadec-9-enoate']
ami = ["4-METHYL-HISTIDINE","P-AMINO BENZAMIDINE","N-{3-[(5R)-3-amino-2,5-dimethyl-1,1-dioxido-5,6-dihydro-2H-1,2,4-thiadiazin-5-yl]-4-fluorophenyl}-5-fluoropyridine-2-carboxamide","N-OXALYLGLYCINE","S-ADENOSYLMETHIONINE","LEUCINE","ARGININE","3-(N-HYDROXYCARBOXAMIDO)-2-ISOBUTYLPROPANOYL-TRP-METHYLAMIDE","7-[4-[4-[2,3-bis(chloranyl)phenyl]piperazin-1-yl]butoxy]-3,4-dihydro-1H-quinolin-2-one","S-ADENOSYL-L-HOMOCYSTEINE","1-benzothiophene-7-carboxylic acid",'3-(5H-DIBENZO[B,F]AZEPIN-5-YL)-N,N-DIMETHYLPROPAN-1-AMINE','GLUTATHIONE']
other = ["N-(tert-butylsulfonyl)-4-fluoro-2-{(3S,4R)-4-hydroxy-3-[(pyridin-2-yl)methyl]-3,4-dihydro-2H-1-benzopyran-7-yl}benzamide","GOLD 3+ ION","PENICILLIN G","N-(3-{5-[5-(1H-INDOL-4-YL)-1,3,4-OXADIAZOL-2-YL]-3-(TRIFLUOROMETHYL)-1H-PYRAZOL-1-YL}BENZYL)-L-ALANINAMIDE","3-[(3,4-dichlorobenzyl)sulfanyl]-N-(methylsulfonyl)thiophene-2-carboxamide","CLINDAMYCIN","RESVERATROL","TETRAETHYLENE GLYCOL","HEXAETHYLENE GLYCOL","8-[(2E)-3-(4-chlorophenyl)prop-2-enoyl]-3-[(3,4-dichlorophenyl)methyl]-1-oxa-3,8-diazaspiro[4.5]decan-2-one","3-(7-DIAMINOMETHYL-NAPHTHALEN-2-YL)-PROPIONIC ACID ETHYL ESTER","ISOPROPYL ALCOHOL","SULFATE ION","DI(HYDROXYETHYL)ETHER","NICKEL (II) ION","SPERMINE","DIMETHYL SULFOXIDE","2-[2-[[3-[4-[(4-methylpiperazin-1-yl)methyl]phenyl]phenyl]carbonylamino]phenyl]ethanoic acid","3-[3-(aminomethyl)phenyl]-~{N}-[(1~{S})-1,2,3,4-tetrahydronaphthalen-1-yl]benzamide","2-(2-{2-[2-(2-METHOXY-ETHOXY)-ETHOXY]-ETHOXY}-ETHOXY)-ETHANOL","7-hydroxy-4-methyl-2H-chromen-2-one","BETA-MERCAPTOETHANOL","NITRATE ION","(4S)-2-METHYL-2,4-PENTANEDIOL","CACODYLATE ION","(6R,7R)-3-(acetyloxymethyl)-7-[[(2Z)-2-(2-amino-1,3-thiazol-4-yl)-2-methoxyimino-ethanoyl]amino]-8-oxo-5-thia-1-azabicy\nclo[4.2.0]oct-2-ene-2-carboxylic acid","CADMIUM ION","(5~{S},8~{S},9~{R})-2-[(~{E})-hex-1-enyl]-8-methoxy-3-methyl-9-oxidanyl-8-(phenylcarbonyl)-1-oxa-7-azaspiro[4.4]non-2-ene-4,6-dione","TETRAFLUOROALUMINATE ION","BROMIDE ION","4-[6-(2-naphthalen-1-ylethoxy)-2,3,4,5-tetrahydro-1H-3-benzazepin-3-ium-3-yl]butanoic acid","PENTAETHYLENE GLYCOL","4-(dipropylsulfamoyl)benzoic acid","Digitonin","1,2-ETHANEDIOL",'COBALT (II) ION',"4-fluoro-N-methyl-N-{4-[6-(propan-2-ylamino)pyrimidin-4-yl]-1,3-thiazol-2-yl}benzamide",'4-[[4-(dimethylamino)cyclohexa-2,5-dien-1-ylidene]-(4-methoxyphenyl)methyl]-N,N-dimethyl-aniline','SODIUM ION','RHODAMINE 6G','4-(2-HYDROXYETHYL)-1-PIPERAZINE ETHANESULFONIC ACID','NONAETHYLENE GLYCOL']

then we can assign these macromolecules and future digestions to their respective nutrients:

B12 (sac + lip): propionate metabolism --> taking amino acids/ odd number fatty acid chains and turning them into propionyl coA, which becomes succinyl coA and joins the krebs cycle to produce ATP

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=11&pidArray=Array&oneDigitRefs=Array

Vitamin C (lip + ami): its is used to regenerate Glutathione,which protects fats from lipid peroxidation from free radicals or other ROS, also used to create 3d structure in proteins with disulfide bonds

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=12&pidArray=Array&oneDigitRefs=Array

Biotin (lip + nuc): it is used to move CO2 or 2c groups. essential for fatty acid synthesis and also used in the nucleus for histone regulation

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=9&pidArray=Array&oneDigitRefs=Array

Pantothenic Acid (lip + sac): essential for movement of acyl groups in the krebs cycle and fatty acid synthesis

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=5&pidArray=Array&oneDigitRefs=Array

Vitamin B6 (ami): used to deaminate, decarboxylate, racemase, in general manipulate amino acids

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=7&pidArray=Array&oneDigitRefs=Array

Folate (nuc): used to synthesize pyrimidines and purines by transfer C groups on its frame

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=10&pidArray=Array&oneDigitRefs=Array

Thiamine (nuc, lip, sac, ami): cleaves and form C-N, C-S, C-O bonds

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=1&pidArray=Array&oneDigitRefs=Array

Vitamin K (sac): serves as an electron carrier in energy transfer

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=13&pidArray=Array&oneDigitRefs=Array

Iron or 'Heme' (sac): acts as an oxygen carrier for oxidative respiration and also acts as a carrier of electrons in the electron transport chain

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=22&pidArray=Array&oneDigitRefs=Array

Riboflavin (sac): invovled in electron transfer

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=3&pidArray=Array&oneDigitRefs=Array

Niacin (sac + nuc): electron transport along with DNA repair

https://www.ebi.ac.uk/thornton-srv/databases/CoFactor/cofactor.php?cid=4&pidArray=Array&oneDigitRefs=Array

Vitamin A (lip): mainly ends up in an acitvated from for the eye, but undergoes series of redox reactions normally performed on lipids to get there

https://www.genome.jp/pathway/map00830+C00473

Vitamin D (lip): plays a role in steroid health and synthesis

https://www.genome.jp/pathway/map00100+C01561

Vitamin E (lip):most closely involved with the formation of fats in the body 

https://www.genome.jp/pathway/map00130+C02477

Calcium (nuc, lip, sac, ami): query has a littany of involvement in biological process

https://www.genome.jp/entry/C00076

Selenium (lip + ami): used to regenerate glutathione enzymes that are used to balance redox in lipids and amino acids

Iodine(ami): if you look at the reactions in this query, they mainly involve tyrosine (an amino acid) getting iodated so that an iodated hormone can be formed

https://www.genome.jp/entry/C01382

phosphorous (ami, nuc, lip, sac): phosphate (which is a phoshphorus bound to 4 oxygen) binds to every kind of macromolecule for signalling

https://www.genome.jp/dbget-bin/www_bfind_sub?mode=bfind&max_hit=1000&locale=en&serv=kegg&dbkey=compound&keywords=phosphate&page=1

magnesium (sac): involved in energy synthesis and binds a lot to ATP 

https://www.sciencedirect.com/science/article/pii/S0009279722003787?via%3Dihub

Zinc(ami): involved in peptidases

https://www.sciencedirect.com/science/article/pii/S0009279722003787?via%3Dihub

copper(sac): electron transfer 

https://www.sciencedirect.com/science/article/pii/S0009279722003787?via%3Dihub

manganese(ami, nuc, lip, sac): used in phosphatase which is used everywhere to remove phosphates which are abundant everywhere in macromolecules

https://www.sciencedirect.com/science/article/pii/S0009279722003787?via%3Dihub

chromium(ami): not a lot of great data on its nutritional value, but it considered for insulin signalling resistance by binding to the protein, insulin

https://www.sciencedirect.com/science/article/pii/S0955286311003044?via%3Dihub

molybdenum(nuc): important in the processing of xanthine (nucleic acid intermediate) into uric acid (waste)

https://www.sciencedirect.com/science/article/pii/S0009279722003787?via%3Dihub

chloride(all): acts mainly as a signal and is present everywhere to maintain charge and osmotic pressure 

https://www.sciencedirect.com/science/article/pii/S0009279722003787?via%3Dihub

potassium(all): acts mainly as a signal and is present everywhere to maintain charge and osmotic pressure 

https://www.sciencedirect.com/science/article/pii/S0009279722003787?via%3Dihub

choline (ami): involved in the synthesis or glycine, serine, and threonine, but more commonly known as a neurotransmitter

https://www.genome.jp/entry/C00114


In [86]:
assignment_dict = {'vitamin_a':vitamin_a, 'vitamin_c':vitamin_c, 'vitamin_d':vitamin_d, 'vitamin_e':vitamin_e, 'vitamin_k':vitamin_k, 'vitamin_b6':vitamin_b6, 'vitamin_b12':vitamin_b12, 'iron':iron, 'calcium':calcium, 'selenium':selenium, 'iodine':iodine, 'thiamin':thiamin, 'riboflavin':riboflavin, 'niacin':niacin, 'folate':folate, 'biotin':biotin, 'pantothenic_acid':pantothenic_acid, 'phosphorus':phosphorus, 'magnesium':magnesium, 'zinc':zinc, 'copper':copper, 'manganese':manganese, 'chromium':chromium, 'molybdenum':molybdenum, 'chloride':chloride, 'potassium':potassium, 'choline':choline}

In [77]:
vitamin_a = vitamin_a + lip
vitamin_c = vitamin_c + lip + ami
vitamin_d = vitamin_d + lip
vitamin_e = vitamin_e + lip
vitamin_k = vitamin_k + sac
vitamin_b6 = vitamin_b6 + ami
vitamin_b12 = vitamin_b12 + sac + lip
iron = iron + sac
calcium = calcium + nuc + lip + sac + ami
selenium = selenium + lip + ami
iodine = iodine + ami
thiamin = thiamin + nuc + lip + ami + sac
riboflavin = riboflavin + sac
niacin = niacin + sac + nuc
folate = folate + nuc
biotin = biotin + lip + nuc
pantothenic_acid = pantothenic_acid + lip + sac
phosphorus = phosphorus + ami + nuc + lip + sac
magnesium = magnesium + sac
zinc = zinc + ami
copper = copper + sac
manganese = manganese + ami + nuc + lip + sac
chromium = chromium + ami
molybdenum = molybdenum + nuc
chloride = chloride + ami + nuc + lip + sac
potassium = potassium + ami + nuc + lip + sac
choline = choline + ami

In [98]:
print (iron)

['FE (III) ION', 'PROTOPORPHYRIN IX CONTAINING FE', 'FE (II) ION', '2-deoxy-2-fluoro-beta-L-fucopyranose', '2-acetamido-2-deoxy-alpha-D-galactopyranose', 'methyl 2-acetamido-3-O-[(1R)-1-carboxyethyl]-2-deoxy-beta-D-glucopyranoside', '2-deoxy-6-O-sulfo-2-(sulfoamino)-alpha-D-glucopyranose', "URIDINE-5'-DIPHOSPHATE-GLUCOSE", 'alpha-D-xylopyranose', 'PHOSPHATIDYLETHANOLAMINE', 'alpha-D-glucopyranose', 'octyl beta-D-glucopyranoside', 'alpha-D-mannopyranose', 'CITRATE ANION', '2-O-sulfo-alpha-L-idopyranuronic acid', 'beta-D-galactopyranose', '2-OXOGLUTARIC ACID', 'alpha-L-fucopyranose', 'nonyl beta-D-glucopyranoside', 'beta-L-fucopyranose', 'L-ALPHA-GLYCEROPHOSPHORYLETHANOLAMINE', '2-acetamido-2-deoxy-beta-D-glucopyranose', 'beta-D-mannopyranose', 'beta-D-fructofuranose', '2-AMINO-2-HYDROXYMETHYL-PROPANE-1,3-DIOL', 'D-MYO-INOSITOL-1,4,5-TRIPHOSPHATE', 'ETHANOL', 'beta-D-glucopyranose', 'CITRIC ACID', 'GLYCEROL', 'beta-D-glucopyranuronic acid', 'alpha-D-galactopyranose', '1,3-PROPANDIOL', 'S

In [88]:
gene_list = [k for k,v in corr_dict.items()]

In [89]:
print (len(gene_list))

307


In [100]:
print (corr_dict['IFI44L'])

['ZINC ION', 'ZINC ION', 'ZINC ION', "ADENOSINE-5'-DIPHOSPHATE", "ADENOSINE-5'-DIPHOSPHATE", "ADENOSINE-5'-DIPHOSPHATE", 'TETRAFLUOROALUMINATE ION', 'TETRAFLUOROALUMINATE ION', 'TETRAFLUOROALUMINATE ION', 'MAGNESIUM ION', 'MAGNESIUM ION', 'MAGNESIUM ION']


In [101]:
def nutr_assignment(gene_dict):
    count = 0
    assigned_dict= {}
    for k,v in gene_dict.items():
            count_dict = {'vitamin_a':0, 'vitamin_c':0, 'vitamin_d':0, 'vitamin_e':0, 'vitamin_k':0, 'vitamin_b6':0, 'vitamin_b12':0, 'iron':0, 'calcium':0, 'selenium':0, 'iodine':0, 'thiamin':0, 'riboflavin':0, 'niacin':0, 'folate':0, 'biotin':0, 'pantothenic_acid':0, 'phosphorus':0, 'magnesium':0, 'zinc':0, 'copper':0, 'manganese':0, 'chromium':0, 'molybdenum':0, 'chloride':0, 'potassium':0, 'choline':0}
            for x in v:
                if x in vitamin_a:
                    count_dict['vitamin_a'] += 1
                if x in vitamin_c:
                    count_dict['vitamin_c'] += 1
                if x in vitamin_d:
                    count_dict['vitamin_d'] += 1
                if x in vitamin_e:
                    count_dict['vitamin_e'] += 1
                if x in vitamin_k:
                    count_dict['vitamin_k'] += 1
                if x in vitamin_b6:
                    count_dict['vitamin_b6'] += 1
                if x in vitamin_b12:
                    count_dict['vitamin_b12'] += 1
                if x in iron:
                    count_dict['iron'] += 1
                if x in calcium:
                    count_dict['calcium'] += 1
                if x in selenium:
                    count_dict['selenium'] += 1
                if x in iodine:
                    count_dict['iodine'] += 1
                if x in thiamin:
                    count_dict['thiamin'] += 1
                if x in riboflavin:
                    count_dict['riboflavin'] += 1
                if x in niacin:
                    count_dict['niacin'] += 1
                if x in folate:
                    count_dict['folate'] += 1
                if x in biotin:
                    count_dict['biotin'] += 1
                if x in pantothenic_acid:
                    count_dict['pantothenic_acid'] += 1
                if x in phosphorus:
                    count_dict['phosphorus'] += 1
                if x in magnesium:
                    count_dict['magnesium'] += 1
                if x in zinc:
                    count_dict['zinc'] += 1
                if x in copper:
                    count_dict['copper'] += 1
                if x in manganese:
                    count_dict['manganese'] += 1
                if x in chromium:
                    count_dict['chromium'] += 1
                if x in molybdenum:
                    count_dict['molybdenum'] += 1
                if x in chloride:
                    count_dict['chloride'] += 1
                if x in potassium:
                    count_dict['potassium'] += 1
                if x in choline:
                    count_dict['choline'] += 1
                else:
                    count += 1
                    print (x)
                    print (count)
            assigned_dict[k] = count_dict
    
    return assigned_dict
                    
            
            
        

    

In [102]:
trial = nutr_assignment(corr_dict)

ZINC ION
1
ZINC ION
2
ZINC ION
3
ADENOSINE-5'-DIPHOSPHATE
4
ADENOSINE-5'-DIPHOSPHATE
5
ADENOSINE-5'-DIPHOSPHATE
6
TETRAFLUOROALUMINATE ION
7
TETRAFLUOROALUMINATE ION
8
TETRAFLUOROALUMINATE ION
9
MAGNESIUM ION
10
MAGNESIUM ION
11
MAGNESIUM ION
12
ZINC ION
13
ZINC ION
14
ZINC ION
15
ZINC ION
16
2-acetamido-2-deoxy-beta-D-glucopyranose
17
1,2-ETHANEDIOL
18
1,2-ETHANEDIOL
19
1,2-ETHANEDIOL
20
1,2-ETHANEDIOL
21
2-acetamido-2-deoxy-beta-D-glucopyranose
22
alpha-L-fucopyranose
23
2-acetamido-2-deoxy-beta-D-glucopyranose
24
alpha-L-fucopyranose
25
PHOSPHATE ION
26
PHOSPHATE ION
27
4-[[4-(dimethylamino)cyclohexa-2,5-dien-1-ylidene]-(4-methoxyphenyl)methyl]-N,N-dimethyl-aniline
28
4-[[4-(dimethylamino)cyclohexa-2,5-dien-1-ylidene]-(4-methoxyphenyl)methyl]-N,N-dimethyl-aniline
29
4-[[4-(dimethylamino)cyclohexa-2,5-dien-1-ylidene]-(4-methoxyphenyl)methyl]-N,N-dimethyl-aniline
30
4-[[4-(dimethylamino)cyclohexa-2,5-dien-1-ylidene]-(4-methoxyphenyl)methyl]-N,N-dimethyl-aniline
31
4-[[4-(dimethylamino

In [103]:
print (trial)

{'IFI44L': {'vitamin_a': 0, 'vitamin_c': 0, 'vitamin_d': 0, 'vitamin_e': 0, 'vitamin_k': 0, 'vitamin_b6': 0, 'vitamin_b12': 0, 'iron': 0, 'calcium': 3, 'selenium': 0, 'iodine': 0, 'thiamin': 3, 'riboflavin': 0, 'niacin': 3, 'folate': 3, 'biotin': 3, 'pantothenic_acid': 0, 'phosphorus': 3, 'magnesium': 0, 'zinc': 3, 'copper': 0, 'manganese': 3, 'chromium': 0, 'molybdenum': 3, 'chloride': 3, 'potassium': 3, 'choline': 0}, 'ADAR': {'vitamin_a': 0, 'vitamin_c': 0, 'vitamin_d': 0, 'vitamin_e': 0, 'vitamin_k': 0, 'vitamin_b6': 0, 'vitamin_b12': 0, 'iron': 0, 'calcium': 0, 'selenium': 0, 'iodine': 0, 'thiamin': 0, 'riboflavin': 0, 'niacin': 0, 'folate': 0, 'biotin': 0, 'pantothenic_acid': 0, 'phosphorus': 0, 'magnesium': 0, 'zinc': 4, 'copper': 0, 'manganese': 0, 'chromium': 0, 'molybdenum': 0, 'chloride': 0, 'potassium': 0, 'choline': 0}, 'TRAF5': {'vitamin_a': 0, 'vitamin_c': 0, 'vitamin_d': 0, 'vitamin_e': 0, 'vitamin_k': 0, 'vitamin_b6': 0, 'vitamin_b12': 0, 'iron': 0, 'calcium': 0, 'sele

In [112]:

values =[[y for x,y in v.items()] for k,v in trial.items()]

In [115]:
data ={}
for x in range(len(values)):
    data[gene_list[x]] = values[x]

In [127]:
df = pd.DataFrame(data=data)

In [131]:
nutrientss = [k for k,v in assignment_dict.items()]

rename_index = {}
for x in range(0,27):
    rename_index[x] = nutrientss[x]
    
df.rename(index=rename_index, inplace=True)
df.head()


IFI44L  ADAR  TRAF5  ARHGAP25  MERTK  MGAT5  COL6A3  TRANK1  \
vitamin_a       0     0      0         0      0      0       0       0   
vitamin_c       0     0      0         0      0      0       0       0   
vitamin_d       0     0      0         0      0      0       0       0   
vitamin_e       0     0      0         0      0      0       0       0   
vitamin_k       0     0      0         0      0      5       0       0   

           MAATS1  PLSCR1  ...  CITED1  MAP2K4P1  PGRMC1  SEPT6  SOWAHD  \
vitamin_a       0       0  ...       0         0       3      0       0   
vitamin_c       0       0  ...       0         0       3      0       0   
vitamin_d       0       0  ...       0         0       3      0       0   
vitamin_e       0       0  ...       0         0       3      0       0   
vitamin_k       0       0  ...       2         0       1      0       4   

           FAM122B  LINC00892  PNMA3  GAB3  RAB39B  
vitamin_a        0          0      0     0       0  
vitamin_c        0          0      0     0       0  
vitamin_d        0          0      0     0       0  
vitamin_e        0          0      0     0       0  
vitamin_k        0          0      0     0       0  

[5 rows x 307 columns]

In [133]:
df_trans = df.T

In [140]:
df_trans.head()

vitamin_a  vitamin_c  vitamin_d  vitamin_e  vitamin_k  vitamin_b6  \
IFI44L            0          0          0          0          0           0   
ADAR              0          0          0          0          0           0   
TRAF5             0          0          0          0          0           0   
ARHGAP25          0          0          0          0          0           0   
MERTK             0          0          0          0          0           0   

          vitamin_b12  iron  calcium  selenium  ...  phosphorus  magnesium  \
IFI44L              0     0        3         0  ...           3          0   
ADAR                0     0        0         0  ...           0          0   
TRAF5               0     0        0         0  ...           0          0   
ARHGAP25            0     0        0         0  ...           0          0   
MERTK               0     0        0         0  ...           0          0   

          zinc  copper  manganese  chromium  molybdenum  chloride  potassium  \
IFI44L       3       0          3         0           3         3          3   
ADAR         4       0          0         0           0         0          0   
TRAF5        0       0          0         0           0         0          0   
ARHGAP25     0       0          0         0           0         0          0   
MERTK        0       0          0         0           0         0          0   

          choline  
IFI44L          0  
ADAR            0  
TRAF5           0  
ARHGAP25        0  
MERTK           0  

[5 rows x 27 columns]

In [137]:
df_2= pd.read_excel('Table_S2.xlsx')
df_2.columns = df_2.iloc[1]
df_2 = df_2.drop([0,1])
df_2.reset_index()
df_2 = df_2.astype({'membership': 'float64'})
df_2 = df_2.astype({'traitsig': 'float64'})
df_2 = df_2.astype({'LV_number': 'category'})

In [142]:
df_merged = df_2.merge(df_trans, left_on='gene', right_on=df_trans.index)

In [143]:
df_merged.head()

module  membership  traitsig        ensg_version      gene LV_number  \
0    red      0.5158    0.2172  ENSG00000137959.15    IFI44L         2   
1    red      0.5497    0.4713  ENSG00000160710.16      ADAR         2   
2    red      0.7754    0.5447  ENSG00000082512.14     TRAF5         2   
3    red      0.7309    0.4325  ENSG00000163219.11  ARHGAP25         2   
4    red      0.5587    0.4396  ENSG00000153208.16     MERTK         2   

                LV_pathway  vitamin_a  vitamin_c  vitamin_d  ...  phosphorus  \
0  MetaMEx_AerobicTraining          0          0          0  ...           3   
1  MetaMEx_AerobicTraining          0          0          0  ...           0   
2  MetaMEx_AerobicTraining          0          0          0  ...           0   
3  MetaMEx_AerobicTraining          0          0          0  ...           0   
4  MetaMEx_AerobicTraining          0          0          0  ...           0   

   magnesium  zinc  copper  manganese  chromium  molybdenum  chloride  \
0          0     3       0          3         0           3         3   
1          0     4       0          0         0           0         0   
2          0     0       0          0         0           0         0   
3          0     0       0          0         0           0         0   
4          0     0       0          0         0           0         0   

   potassium  choline  
0          3        0  
1          0        0  
2          0        0  
3          0        0  
4          0        0  

[5 rows x 34 columns]

In [144]:
df_merged.to_csv('retry_data_wrangle.csv')

7/5

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df = pd.read_csv('retry_data_wrangle.csv')

In [3]:
df_add = pd.read_csv('actual_dietary_suggestions - Sheet1.csv')

In [4]:
df.head()

Unnamed: 0 module  membership  traitsig        ensg_version      gene  \
0           0    red      0.5158    0.2172  ENSG00000137959.15    IFI44L   
1           1    red      0.5497    0.4713  ENSG00000160710.16      ADAR   
2           2    red      0.7754    0.5447  ENSG00000082512.14     TRAF5   
3           3    red      0.7309    0.4325  ENSG00000163219.11  ARHGAP25   
4           4    red      0.5587    0.4396  ENSG00000153208.16     MERTK   

   LV_number               LV_pathway  vitamin_a  vitamin_c  ...  phosphorus  \
0        2.0  MetaMEx_AerobicTraining          0          0  ...           3   
1        2.0  MetaMEx_AerobicTraining          0          0  ...           0   
2        2.0  MetaMEx_AerobicTraining          0          0  ...           0   
3        2.0  MetaMEx_AerobicTraining          0          0  ...           0   
4        2.0  MetaMEx_AerobicTraining          0          0  ...           0   

   magnesium  zinc  copper  manganese  chromium  molybdenum  chloride  \
0          0     3       0          3         0           3         3   
1          0     4       0          0         0           0         0   
2          0     0       0          0         0           0         0   
3          0     0       0          0         0           0         0   
4          0     0       0          0         0           0         0   

   potassium  choline  
0          3        0  
1          0        0  
2          0        0  
3          0        0  
4          0        0  

[5 rows x 35 columns]

In [5]:
df = df.drop(columns = ['Unnamed: 0','module','ensg_version','LV_number','LV_pathway'])

In [6]:
df.head()

membership  traitsig      gene  vitamin_a  vitamin_c  vitamin_d  vitamin_e  \
0      0.5158    0.2172    IFI44L          0          0          0          0   
1      0.5497    0.4713      ADAR          0          0          0          0   
2      0.7754    0.5447     TRAF5          0          0          0          0   
3      0.7309    0.4325  ARHGAP25          0          0          0          0   
4      0.5587    0.4396     MERTK          0          0          0          0   

   vitamin_k  vitamin_b6  vitamin_b12  ...  phosphorus  magnesium  zinc  \
0          0           0            0  ...           3          0     3   
1          0           0            0  ...           0          0     4   
2          0           0            0  ...           0          0     0   
3          0           0            0  ...           0          0     0   
4          0           0            0  ...           0          0     0   

   copper  manganese  chromium  molybdenum  chloride  potassium  choline  
0       0          3         0           3         3          3        0  
1       0          0         0           0         0          0        0  
2       0          0         0           0         0          0        0  
3       0          0         0           0         0          0        0  
4       0          0         0           0         0          0        0  

[5 rows x 30 columns]

In [7]:
df_add.head()

nutrients  suggested_intake
0  vitamin_a             900.0
1  vitamin_c              90.0
2  vitamin_d              20.0
3  vitamin_e              15.0
4  vitamin_k             120.0

In [24]:
def metabolic_proportion(df1, df2):
    meta_prop = {}
    for x in range(27):
        prop_list = []
        sum_n = (df.iloc[:,x+3].sum())+307
        for y in df.iloc[:,x+3]:
            if y == 0:
                prop_list.append((1/sum_n)*df2.iloc[x,1])
            elif y != 0:
                prop_list.append(((y+1)/sum_n)*df2.iloc[x,1])
            else:
                print ('something went wrong')
        meta_prop[df1.columns[x+3]] = prop_list
    
    return meta_prop
            

In [25]:
meta_prop = metabolic_proportion(df, df_add)

In [26]:
print (meta_prop)

{'vitamin_a': [2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 4.749340369393139, 2.3746701846965697, 2.3746701846965697, 4.749340369393139, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 26.12137203166227, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.3746701846965697, 2.374670

In [27]:
df_meta_prop = pd.DataFrame(data=meta_prop)

In [34]:
df = df.drop (columns = df_meta_prop.columns)

In [35]:
df_concat = pd.concat([df, df_meta_prop], axis=1) 

In [36]:
df_concat.head()

membership  traitsig      gene  vitamin_a  vitamin_c  vitamin_d  vitamin_e  \
0      0.5158    0.2172    IFI44L    2.37467    0.22113    0.05277   0.039578   
1      0.5497    0.4713      ADAR    2.37467    0.22113    0.05277   0.039578   
2      0.7754    0.5447     TRAF5    2.37467    0.22113    0.05277   0.039578   
3      0.7309    0.4325  ARHGAP25    2.37467    0.22113    0.05277   0.039578   
4      0.5587    0.4396     MERTK    2.37467    0.22113    0.05277   0.039578   

   vitamin_k  vitamin_b6  vitamin_b12  ...  phosphorus  magnesium      zinc  \
0   0.152284     0.00506      0.00281  ...    5.296610   0.532995  0.111675   
1   0.152284     0.00506      0.00281  ...    1.324153   0.532995  0.139594   
2   0.152284     0.00506      0.00281  ...    1.324153   0.532995  0.027919   
3   0.152284     0.00506      0.00281  ...    1.324153   0.532995  0.027919   
4   0.152284     0.00506      0.00281  ...    1.324153   0.532995  0.027919   

     copper  manganese  chromium  molybdenum  chloride  potassium   choline  
0  0.001136    0.00984  0.104167    0.493151  9.613375  20.215054  1.622419  
1  0.001136    0.00246  0.104167    0.123288  2.403344   5.053763  1.622419  
2  0.001136    0.00246  0.104167    0.123288  2.403344   5.053763  1.622419  
3  0.001136    0.00246  0.104167    0.123288  2.403344   5.053763  1.622419  
4  0.001136    0.00246  0.104167    0.123288  2.403344   5.053763  1.622419  

[5 rows x 30 columns]

In [37]:
df_concat.to_csv('prop_wrangled.csv')

generate a version where all of the complete zero rows are dropped but the proportions are accurate

In [1]:
import pandas as pd

In [16]:
df = pd.read_csv('retry_data_wrangle.csv')

In [17]:
df_add = pd.read_csv('actual_dietary_suggestions - Sheet1.csv')

In [18]:
df = df.drop(columns = ['Unnamed: 0','module','ensg_version','LV_number','LV_pathway'])

In [19]:
df_drop = df.drop(columns=['gene','membership','traitsig'])

In [20]:
def df_dropper(df):
    ind = []
    for x in range(len(df)):
        if df.iloc[x].sum() == 0:
            ind.append(x)
    return ind

In [21]:
ind = df_dropper(df_drop)

In [22]:
df = df.drop(index=ind)

In [23]:
df.reset_index(inplace=True)

In [26]:
df = df.drop(columns='index')

In [27]:
df.head()

membership  traitsig    gene  vitamin_a  vitamin_c  vitamin_d  vitamin_e  \
0      0.5158    0.2172  IFI44L          0          0          0          0   
1      0.5497    0.4713    ADAR          0          0          0          0   
2      0.6029    0.5140   MGAT5          0          0          0          0   
3      0.4493    0.3355  COL6A3          0          0          0          0   
4      0.6431    0.7271    GNB4          0          0          0          0   

   vitamin_k  vitamin_b6  vitamin_b12  ...  phosphorus  magnesium  zinc  \
0          0           0            0  ...           3          0     3   
1          0           0            0  ...           0          0     4   
2          5           0            5  ...           5          5     0   
3          0           0            0  ...           2          0     0   
4          1           0            1  ...           1          1     0   

   copper  manganese  chromium  molybdenum  chloride  potassium  choline  
0       0          3         0           3         3          3        0  
1       0          0         0           0         0          0        0  
2       5          5         0           0         5          5        0  
3       0          0         0           0         0          0        0  
4       1          1         0           0         1          1        0  

[5 rows x 30 columns]

In [28]:
def metabolic_proportion_v2(df1, df2):
    meta_prop = {}
    for x in range(27):
        prop_list = []
        sum_n = (df.iloc[:,x+3].sum() + len(df))
        for y in df.iloc[:,x+3]:
            if y == 0:
                prop_list.append((1/sum_n)*df2.iloc[x,1])
            elif y != 0:
                prop_list.append(((y+1)/sum_n)*df2.iloc[x,1])
            else:
                print ('something went wrong')
        meta_prop[df1.columns[x+3]] = prop_list
    
    return meta_prop

In [29]:
meta_prop_v2 = metabolic_proportion_v2(df, df_add)

In [30]:
df_meta_prop_v2 = pd.DataFrame(data=meta_prop_v2)

In [31]:
df = df.drop (columns = df_meta_prop_v2.columns)

In [32]:
df_concat_v2 = pd.concat([df, df_meta_prop_v2], axis=1) 

In [33]:
df_concat_v2.iloc[1]

membership            0.5497
traitsig              0.4713
gene                    ADAR
vitamin_a           4.663212
vitamin_c            0.40724
vitamin_d           0.103627
vitamin_e            0.07772
vitamin_k           0.199336
vitamin_b6          0.011333
vitamin_b12         0.003593
iron                0.029508
calcium             1.581509
selenium            0.248869
iodine              0.974026
thiamin             0.001613
riboflavin          0.002131
niacin               0.02406
folate              2.234637
biotin              0.119522
pantothenic_acid    0.007452
phosphorus          1.649077
magnesium           0.697674
zinc                0.264423
copper              0.001485
manganese           0.003071
chromium            0.233333
molybdenum          0.251397
chloride            2.983139
potassium           6.317204
choline             3.594771
Name: 1, dtype: object

In [34]:
print (len(df_concat_v2))

121


In [36]:
df_concat_v2.to_csv('final_wrangle.csv')